Repository hmcts/juror-bureau, pull requests merged in 2024-04, with the labels that each got.

#85 feature/JM-6114: Allow edit of for-approval, for-reapproval and approved expenses
  client/templates/expenses/_partials/food-and-drink.njk
  client/templates/expenses/_partials/recalculate-error-banner.njk
  client/templates/expenses/_partials/time.njk
  client/templates/expenses/edit/edit-approval-expenses-list.njk
  client/templates/expenses/enter-expenses-non-attendance.njk
  client/templates/expenses/loss-over-limit.njk
  client/templates/expenses/total-less-than-zero.njk
  client/templates/expenses/travel-over-limit.njk
  server/config/validation/edit-approved-expenses.js
  server/objects/court-location.js
  server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
  server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js
  server/routes/juror-management/expenses/enter-expenses/index.js
  server/routes/juror-management/expenses/non-attendance-day/non-attendance-day.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-85

#104 integrate axios to start using with the application for new api requests
  Gruntfile.js
  package.json
  server/app.js
  server/components/logger/index.js
  server/objects/axios-instance.js
  server/objects/dataAccessObject.js
  server/objects/index.js
  server/objects/request-pool.js
  server/routes/pool-management/pool-management.controller.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-104

#128 hotfix/JM-6716 - Invalid assignment to const
  server/routes/juror-management/reassign/reassign.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-128

#131 JM-6694: Print a next attendance date report
  client/templates/reporting/standard-reports/pool-search.njk
  client/templates/reporting/standard-reports/standard-report.njk
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-131

#132 fix undefined function on default expenses
  server/objects/expenses.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-132

#134 hotfix/JM-6688
  server/routes/response/detail/detail.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-134

#137 feature/JM-6400: Undelivered List Report
  client/templates/reporting/index.njk
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-137

#129 feature/jm-5969- failed to attend letters
  client/templates/documents/_common/letters-list.njk
  client/templates/documents/index-court.njk
  client/templates/juror-management/juror-record/_partials/attendance-table.njk
  server/lib/mod-utils.js
  server/routes/documents/failed-to-attend/failed-to-attend.controller.js
  server/routes/documents/failed-to-attend/index.js
  server/routes/documents/index.js
  server/routes/documents/letters-list/letters-list.controller.js
  server/routes/documents/pdf/letter-templates.js
  server/routes/documents/print.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-129

#139 hotfix/JM-6670 - Shouldn't be able to process a super urgent response
  client/templates/response/_partials/update-header.njk
  client/templates/response/detail.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-139

#141 feature/JM-6259: Send/Resend Summons reminder letter
  server/lib/mod-utils.js
  server/routes/documents/helper/table-generator.js
  server/routes/documents/letters-list/letters-list.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-141

#142 remove debugger kw
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-142

#144 fix change next due at court date
  server/routes/juror-management/juror-record/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-144

#136 feature/jm-5963- As a jury I need to be able to print a certificate of attendance (FE)
  client/templates/documents/index-court.njk
  server/lib/mod-utils.js
  server/routes/documents/document-form.controller.js
  server/routes/documents/letters-list/letters-list.controller.js
  server/routes/documents/pdf/letter-generator.js
  server/routes/documents/pdf/letter-templates.js
  server/routes/documents/print.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-136

#143 add samesite strict config to cookies
  server/lib/session-config.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-143

#149 hotfix/JM-6720
  server/routes/juror-management/attendance/change-times/change-times.controller.js
  server/routes/juror-management/juror-management.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-149

#151 Bug (JM-6814) fix sending juror numbers as string instead of array
  server/routes/pool-management/pool-overview/change-next-due-at-court/change-next-due-at-court.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-151

#152 fix confirm attendance day
  server/routes/juror-management/attendance/confirm-attendance/confirm-attendance.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-152

#154 fix phone number regex
  server/config/validation/paper-reply.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-154

#156 add logging to stdout back into production
  server/config/environment/production.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-156

#155 JM-6823: 'generate panel' button should not be visible
  client/templates/trial-management/trial-detail.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-155

#157 hotfix/JM-6846
  server/routes/juror-management/attendance/confirm-attendance/confirm-attendance.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-157

#153 Bug (JM-6779) fix nil pool display message and court nil pool flow
  client/templates/pool-management/pool-overview/court-pool-overview.njk
  server/routes/pool-management/request-pool/request-pool.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-153

#159 hotfix/JM-6872
  server/routes/summons-management/update/cjs-employment.controller.js
  server/routes/summons-management/update/eligibility.controller.js
  server/routes/summons-management/update/reasonable-adjustments.controller.js
  server/routes/summons-management/update/reply-type.controller.js
  server/routes/summons-management/update/signature.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-159

#162 JM-6009: remove permissions and add bureau user condition
  client/templates/response/_partials/update-header.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-162

#164 fix/appinsights-logger
  server/app.js
  server/config/environment/index.js
  server/lib/appinsights.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-164

#138 feature/JM-6753
  client/templates/juror-management/_partials/attendance-sub-nav.njk
  client/templates/juror-management/attendance.njk
  client/templates/juror-management/jurors-on-trial/confirm-attendance.njk
  client/templates/juror-management/jurors-on-trial/list-of-trials.njk
  client/templates/juror-management/jurors-on-trial/trials-table.njk
  server/components/filters/filters.spec.js
  server/components/filters/index.js
  server/config/validation/change-attendance-times.js
  server/config/validation/jurors-on-trial.js
  server/lib/mod-utils.js
  server/lib/mod-utils.spec.js
  server/lib/utils.spec.js
  server/objects/index.js
  server/objects/juror-attendance.js
  server/objects/jurors-on-trial.js
  server/routes/juror-management/index.js
  server/routes/juror-management/jurors-on-trial/index.js
  server/routes/juror-management/jurors-on-trial/jurors-on-trial.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-138

#165 Bug (JM-6814) fix crash on empty bulk next due at court
  server/config/validation/change-attendance-date.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-165

#169 Bug (JM-6875) replace generic error with specific error banner
  server/lib/mod-utils.js
  server/routes/trial-management/generate-panel/generate-panel.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-169

#166 hotfix/JM-6757: Police check statuses
  client/templates/juror-management/juror-record/overview.njk
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-166

#150 feature/JM-6598: juror identity check
  client/templates/juror-management/juror-record/confirm-identity.njk
  client/templates/juror-management/juror-record/overview.njk
  server/config/validation/confirm-identity.js
  server/objects/administration.js
  server/objects/confirm-identity.js
  server/objects/index.js
  server/routes/juror-management/juror-record/confirm-identity/confirm-identity.controller.js
  server/routes/juror-management/juror-record/confirm-identity/index.js
  server/routes/juror-management/juror-record/index.js
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-150

#171 hotfix/JM-6945: Updated adminstration delete judge condition
  client/templates/administration/judges/judges.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-171

#173 hotfix/juror-record-overview-response: fixed resolve police check in juror record overview
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-173

#172 JDB-5557 - Dashboard FE - Chart label/tooltip rendering
  server/routes/dashboard/dashboard.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-172

#177 use pool location code
  server/routes/pool-management/pool-overview/pool-overview.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-177

#175 jm-6870: If defendant name longer than 16 chars on create trial, it fails
  server/config/validation/create-trial.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-175

#160 hotfix/JM-5853 & hotfix/JM-6868
  client/templates/response/_partials/update-header.njk
  server/objects/index.js
  server/objects/status.js
  server/objects/status.spec.js
  server/routes/response/detail/detail.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-160

#178 hotfix/JM-6671: Removed 'check can accommodate button' if response status is closed
  client/templates/response/_partials/reasonable-adjustments.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-178

#179 hotfix/JM-4253
  server/lib/mod-utils.js
  server/objects/response-detail.js
  server/routes/response/detail/detail.controller.js
  server/routes/summons-management/summons-management.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-179

#181 Bug (JM-6935, JM-6936) hide 'add non-attendance day' except in good statuses
  client/templates/juror-management/expense-record/expense-record.njk
  client/templates/juror-management/juror-record/attendance.njk
  server/objects/juror-record.js
  server/routes/juror-management/juror-record/juror-record.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/draft.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-181

#180 hotfix/JM-6733: Error on create juror record postcode
  server/config/validation/record-create-manual.js
  server/routes/juror-management/create-record-manual/create-record-manual.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-180

#182 feature/JM-6598
  client/templates/juror-management/juror-record/confirm-identity.njk
  server/config/validation/confirm-identity.js
  server/routes/juror-management/juror-record/confirm-identity/confirm-identity.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-182

#183 hotfix/JM-6960 & hotfix/JM-6962
  client/templates/pool-management/pool-overview/pool-history.njk
  server/routes/pool-management/pool-overview/pool-overview.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-183

#184 Bug (JM-6936) block adding attendance days for bad juror states
  client/templates/juror-management/juror-record/attendance.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-184

#186 Bug (JM-5051) fix court visibility of court owned jurors in inactive pools
  client/templates/pool-management/pool-overview/court-pool-jurors.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-186

#189 Bug (JM-4673) block negative number of jurors from being summoned
  client/templates/pool-management/_common/check-request-details.njk
  server/lib/mod-utils.js
  server/routes/pool-management/request-pool/request-pool.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-189

#190 hotfix/JM-6827: show cause letter issues
  client/templates/custom-components/letter-flow/redirect.njk
  client/templates/juror-management/juror-record/attendance.njk
  server/routes/documents/print.controller.js
  server/routes/documents/show-cause/show-cause.controller.js
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-190

#196 Bug (JM-6583) Fix certificate of attendance crashing with no expenses
  server/routes/documents/print.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-196

#194 hotfix/JM-6064
  client/templates/juror-management/juror-record/overview.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-194

#192 hotfix/JM-6934: Locked Bureau pool view once pool transferred to court
  client/templates/pool-management/pool-overview/bureau-pool-overview.njk
  server/routes/pool-management/pool-overview/pool-overview.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-192

#195 hotfix/JM-6778: Court User - Reassign 'Create new pool' option
  client/templates/juror-management/reassign/pools.njk
  server/config/validation/pool-management.js
  server/routes/juror-management/reassign/reassign.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-195

#197 feature/JM-6521
  client/templates/juror-management/juror-record/expenses.njk
  server/objects/index.js
  server/objects/juror-record.js
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-197

#187 hotfix/JM-6933: Fixed rendering for court pool history
  server/routes/pool-management/pool-overview/pool-overview.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-187

#185 hotfix/JM-6780
  client/templates/response/process/responded.njk
  server/objects/status.js
  server/objects/summons-management.js
  server/routes/juror-management/update/index.js
  server/routes/juror-management/update/juror-update.controller.js
  server/routes/juror-management/update/juror-update.responded.controller.js
  server/routes/response/detail/detail.controller.js
  server/routes/summons-management/paper-reply/paper-reply.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-185

#200 hotfix/JM-6776: Lock expense approval to court managers only
  client/templates/juror-management/_common/juror-management-nav.njk
  server/routes/juror-management/approve-expenses/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-200

#191 hotfix/JM-6781
  client/templates/summons-management/process-reply/disqualify.njk
  server/objects/disqualify-mod.js
  server/routes/juror-management/juror-record/juror-record.controller.js
  server/routes/juror-management/update/index.js
  server/routes/juror-management/update/juror-update.controller.js
  server/routes/juror-management/update/juror-update.disqualify.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-191

#201 hotfix/JM-6983
  server/objects/response-detail.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-201

#202 Court Users - Hide pool history tab until transferred to court
  client/templates/pool-management/pool-overview/_partials/sub-nav.njk
  server/routes/pool-management/pool-overview/pool-overview.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-202

#203 Code Optimisations for your work page
  server/objects/responses.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-203

#204 revert jm-6984 changes
  server/objects/responses.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-204

#208 hotfix/JM-6781
  server/routes/juror-management/update/juror-update.disqualify.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-208

#210 hotfix/jm-6947- Entering a Courtroom name that is longer then 6 character causes. (same occurs for room description longer then 30). Sorry, there is a technical problem
  server/config/validation/create-courtroom.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-210

#209 hotfix/jm-6944- Entering a Judge code that is longer then 4 character causes issues
  server/config/validation/edit-judge.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-209

#213 hotfix/JM-6982
  server/routes/documents/letters-list/letters-list.controller.js
  server/routes/documents/pdf/letter-generator.js
  server/routes/documents/pdf/letter-templates.js
  server/routes/documents/print.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-213

#206 hotfix/JM-6009-b
  client/templates/response/_partials/update-header.njk
  client/templates/response/process/send-to.njk
  server/routes/response/detail/detail.controller.js
  server/routes/staff/staff.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-206

#212 hotfix/JM-6729
  client/templates/juror-management/juror-record/_partials/attendance-table.njk
  client/templates/juror-management/juror-record/modify-attendance.njk
  server/config/validation/change-jurors-attendance.js
  server/config/validation/modify-jurors-attendance.js
  server/objects/index.js
  server/objects/juror-attendance.js
  server/routes/juror-management/juror-record/change-attendance/change-attendance.controller.js
  server/routes/juror-management/juror-record/index.js
  server/routes/juror-management/juror-record/modify-attendance/modify-attendance.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-212

#211 hotfix/JM-6697
  client/templates/documents/_common/document-form.njk
  server/config/validation/document-form.js
  server/config/validation/edit-juror-details.js
  server/config/validation/paper-reply.js
  server/config/validation/record-create-manual.js
  server/lib/mod-utils.js
  server/routes/documents/document-form.controller.js
  server/routes/documents/letters-list/letters-list.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-211

#214 hotfix/JM-7020
  client/templates/juror-management/juror-record/overview.njk
  client/templates/trial-management/_partials/trial-panel.njk
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-214

#217 JM-6939: If I try to check in a juror that has failed I get a message indicating they are already checked in but infact they are not
  client/js/attendance.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-217

#219 Make at court tab priority for court users
  server/routes/pool-management/pool-management.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-219

#216 hotfix/JM-6963: Added court auth to trial management routes
  client/templates/custom-components/super-navigation/super-navigation.njk
  server/routes/trial-management/add-panel-members/index.js
  server/routes/trial-management/create-trial/index.js
  server/routes/trial-management/edit-trial/index.js
  server/routes/trial-management/empanel-jury/index.js
  server/routes/trial-management/generate-panel/index.js
  server/routes/trial-management/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-216

#218 hotfix/JM-7018: Fix rights for juror management nav
  client/templates/juror-management/_common/juror-management-nav.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-218

#220 hotfix/JM-6227: Display list with jurors who had statuses changed when sending to print
  client/templates/documents/status-changed.njk
  server/routes/documents/index.js
  server/routes/documents/letters-list/letters-list.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-220

#223 hotfix/JM-7045
  client/templates/summons-management/_common/details-banner-new.njk
  server/routes/response/detail/detail.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-223

#224 feature/JM-6528
  server/routes/juror-management/unpaid-attendance/expense-record/draft.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-224

#221 hotifx/JM-7023: Fixed issue for expenses tab if juror has no attendances
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-221

#227 Disfunctional header link
  client/templates/layouts/govuk_template.njk
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-227

#228 Incorrect label content for search button
  client/templates/custom-components/super-navigation/super-navigation.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-228

#234 fix tab not setting properly
  server/routes/pool-management/pool-management.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-234

#236 fix jurors attending table count
  client/js/attendance.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-236

#232 hotfix/JM-6587: Add error for empty bank details
  server/config/validation/bank-details.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-232

#226 Table header aria-labels
  client/templates/administration/bank-holidays.njk
  client/templates/administration/courts-and-bureau.njk
  client/templates/administration/judges/judges.njk
  client/templates/administration/non-sitting-days.njk
  client/templates/administration/room-locations/rooms.njk
  client/templates/administration/system-codes.njk
  client/templates/administration/users/assign-courts/_partials/assign-courts-table.njk
  client/templates/administration/users/assign-courts/remove-court.njk
  client/templates/administration/users/user-record.njk
  client/templates/allocation/index.njk
  client/templates/completed.njk
  client/templates/custom-components/sortable-table/template.njk
  client/templates/documents/exemption/certificate-of-exemption.njk
  client/templates/documents/exemption/exemption-list.njk
  client/templates/inbox.njk
  client/templates/juror-management/approve-expenses/_partials/approve-expenses-table.njk
  client/templates/juror-management/attendance/check-out-panelled.njk
  client/templates/juror-management/attendance/confirm-attendance.njk
  client/templates/juror-management/attendance/confirmed/confirmed.njk
  client/templates/juror-management/attendance/not-checked-out.njk
  client/templates/juror-management/attendance/unconfirmed/unconfirmed.njk
  client/templates/juror-management/dismiss-jurors/check-out.njk
  client/templates/juror-management/dismiss-jurors/jurors-table.njk
  client/templates/juror-management/dismiss-jurors/pools-table.njk
  client/templates/juror-management/expense-record/_partials/approval-table.njk
  client/templates/juror-management/expense-record/_partials/approved-table.njk
  client/templates/juror-management/juror-record/_partials/attendance-table.njk
  client/templates/juror-management/jurors-on-trial/confirm-attendance.njk
  client/templates/juror-management/jurors-on-trial/trials-table.njk
  client/templates/juror-management/manage-jurors/pending-approval.njk
  client/templates/juror-management/manage-jurors/pools.njk
  client/templates/juror-management/search/index.njk
  client/templates/pending.njk
  client/templates/pool-management/deferral-maintenance/_partials/deferrals-table.njk
  client/templates/pool-management/pool-overview/coroner.njk
  client/templates/pool-management/pool-search/index.njk
  client/templates/reporting/some-report/index.njk
  client/templates/reporting/standard-reports/pool-search.njk
  client/templates/search/index.njk
  client/templates/staff/index.njk
  client/templates/trial-management/_partials/trial-panel.njk
  server/routes/documents/helper/table-generator.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-226

#215 hotfix/JM-6959: Handle when pool overview returns over 500 members
  client/templates/pool-management/pool-overview/bureau-pool-jurors.njk
  client/templates/pool-management/pool-overview/court-pool-jurors.njk
  server/routes/pool-management/pool-overview/pool-overview.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-215

#238 force build
  README.md
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-238

#239 fix the system-codes views
  client/templates/administration/system-codes.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-239

#241 hotfix/JM-7011 - Unnecessary has leading '-'
  client/templates/juror-management/juror-record/overview.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-241

#235 hotfix/JM-7022: Added check in field to return jurors without confirming
  client/templates/trial-management/returns/confirm-return.njk
  server/config/validation/return-panel-jury.js
  server/routes/trial-management/returns.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-235

#237 task/JM-7069
  client/templates/trial-management/empanel-jury/select-jurors.njk
  server/routes/trial-management/empanel-jury/empanel-jury.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-237

#244 hotfix/JM-7089
  server/routes/documents/helper/table-generator.js
  server/routes/documents/letters-list/letters-list.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-244

#245 hotfix/JM-7108
  client/templates/juror-management/attendance/confirm-attendance.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-245

#230 hotfix/JM-7044: Switched staff rank checks to isTeamLeader
  client/templates/includes/send-to.njk
  client/templates/response/_partials/update.njk
  client/templates/response/process/send-to.njk
  client/templates/search/index.njk
  server/components/auth/index.js
  server/config/validation/custom-validation.js
  server/routes/search/search.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-230

#248 hotfix/Pending-Approval-Fix
  client/templates/juror-management/manage-jurors/pending-approval.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-248

#253 Hotfix/jm 6995
  client/scss/01-settings/_typography.scss
  client/scss/05-objects/_headings.scss
  client/scss/05-objects/_navs.scss
  client/scss/05-objects/_tables.scss
  client/scss/06-components/_backlog.scss
  client/scss/06-components/_calllog.scss
  client/scss/06-components/_changelog.scss
  client/scss/06-components/_edit.scss
  client/scss/06-components/_icons.scss
  client/scss/06-components/_response.scss
  client/scss/06-components/_search.scss
  client/scss/custom-components/_ds-datepicker.scss
  client/scss/custom-components/_pool-record-doughnut.scss
  client/scss/custom-components/_super-navigation.scss
  client/scss/dashboard.scss
  client/scss/exemption-document.scss
  client/scss/jd-custom.scss
  client/scss/main.scss
  client/scss/mod-custom.scss
  client/scss/pool-overview.scss
  client/scss/summoning-progress.scss
  client/scss/trial-detail.scss
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-253

#254 hotfix/JM-7093 - Can't see admin page as a normal officer
  client/templates/administration/_common/court-administration-nav.njk
  client/templates/administration/court-details.njk
  client/templates/administration/expense-limits-court.njk
  client/templates/custom-components/super-navigation/super-navigation.njk
  server/routes/administration/court-details/index.js
  server/routes/administration/expense-limits-court/index.js
  server/routes/administration/judges/index.js
  server/routes/administration/non-sitting-days/non-sitting-days.controller.js
  server/routes/administration/room-locations/index.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-254

#246 feature/JM-6398: Non-responded report
  client/templates/layouts/default.njk
  client/templates/reporting/_common/court-reports-nav.njk
  client/templates/reporting/bureau-reports.njk
  client/templates/reporting/court-reports.njk
  client/templates/reporting/court-statistics.njk
  client/templates/reporting/index.njk
  server/routes/reporting/index.js
  server/routes/reporting/reporting.controller.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-246

#242 Added edit functionality to trials
  client/templates/trial-management/confirm-protected-trial.njk
  client/templates/trial-management/create-trial.njk
  client/templates/trial-management/trial-detail.njk
  server/objects/create-trial.js
  server/objects/index.js
  server/routes/trial-management/create-trial/create-trial.controller.js
  server/routes/trial-management/edit-trial/edit-trial.controller.js
  server/routes/trial-management/edit-trial/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-242

#247 Feature (JM-7046) implements bulk postpone from deferral maintenance
  client/templates/pool-management/deferral-maintenance/_partials/deferrals-table.njk
  client/templates/pool-management/deferral-maintenance/index.njk
  server/routes/juror-management/postpone/index.js
  server/routes/juror-management/postpone/postpone.controller.js
  server/routes/pool-management/deferral-maintenance/deferral-maintenance.controller.js
  server/routes/pool-management/deferral-maintenance/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-247

#252 Reassigning a juror to new pool clears attendance records.
  server/objects/juror-record.js
  server/routes/juror-management/attendance/change-attendance-date/change-attendance-date.controller.js
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-252

#256 hotfix/JM-7077 - Users requesting a home page button
  client/templates/layouts/govuk_template.njk
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-256

#251 Feature/JM-6467: Postponed list reports
  client/scss/mod-custom.scss
  client/templates/reporting/bureau-reports.njk
  client/templates/reporting/court-reports.njk
  client/templates/reporting/standard-reports/pool-search.njk
  client/templates/reporting/standard-reports/search-by/postponed.njk
  client/templates/reporting/standard-reports/standard-report.njk
  server/config/validation/report-search-by.js
  server/lib/reports/default-layout.js
  server/routes/reporting/index.js
  server/routes/reporting/postponed-report/index.js
  server/routes/reporting/postponed-report/postponed.controller.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, stg/add-or-update, rel:juror-bureau-pr-251

#250 task/JM-7124: Expenses journeys updates
  client/js/expenses-summary.js
  client/templates/expenses/_partials/payment-method.njk
  client/templates/expenses/edit/edit-approval-expenses-list.njk
  client/templates/expenses/edit/expenses-table.njk
  client/templates/expenses/enter-expenses-non-attendance.njk
  client/templates/expenses/enter-expenses.njk
  client/templates/juror-management/approve-expenses/_partials/approve-expenses-table.njk
  client/templates/juror-management/expense-record/_partials/sub-nav.njk
  server/lib/mod-utils.js
  server/objects/expense-record.js
  server/objects/expense-record.spec.js
  server/objects/expenses.js
  server/objects/juror-record.js
  server/routes/juror-management/approve-expenses/approve-expenses.controller.js
  server/routes/juror-management/approve-expenses/index.js
  server/routes/juror-management/edit/juror-edit.controller.js
  server/routes/juror-management/expenses/edit-bank-details/edit-bank-details.controller.js
  server/routes/juror-management/expenses/edit-bank-details/index.js
  server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
  server/routes/juror-management/expenses/edit/index.js
  server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js
  server/routes/juror-management/expenses/enter-expenses/index.js
  server/routes/juror-management/expenses/expenses.controller.js
  server/routes/juror-management/expenses/index.js
  server/routes/juror-management/expenses/non-attendance-day/non-attendance-day.controller.js
  server/routes/juror-management/juror-record/index.js
  server/routes/juror-management/juror-record/juror-record.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/add-smartcard-spend.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/draft.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/expense-record.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/for-approval.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/index.js
  server/routes/juror-management/unpaid-attendance/unpaid-attendance.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-250

#263 Reasonable adjustments contains None and N - None
  client/templates/juror-management/juror-record/overview.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-263

#266 hotfix/JM-7061 - Define the number of motorcycle passengers
  client/js/expenses-summary.js
  client/templates/expenses/_partials/travel.njk
  server/config/validation/enter-expenses.js
  server/config/validation/enter-expenses.spec.js
  server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-266

#275 hotfix/JM-7304: Sortable expenses
  client/templates/juror-management/expense-record/_partials/approval-table.njk
  client/templates/juror-management/expense-record/_partials/expenses-table-macros.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-275

#277 hotfix/JM-7146
  server/routes/administration/system-codes/system-codes.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-277

#272 Feat/jm 6379
  client/templates/custom-components/super-navigation/super-navigation.njk
  client/templates/reporting/_common/court-reports-nav.njk
  client/templates/reporting/court-reports.njk
  client/templates/reporting/court-statistics.njk
  client/templates/reporting/incomplete-service/cutoff-date.njk
  client/templates/reporting/standard-reports/pool-search.njk
  client/templates/reporting/standard-reports/standard-report.njk
  server/components/auth/index.js
  server/objects/reports.js
  server/routes/reporting/incomplete-service/incomplete-service.controller.js
  server/routes/reporting/incomplete-service/index.js
  server/routes/reporting/index.js
  server/routes/reporting/postponed-report/postponed.controller.js
  server/routes/reporting/reporting.controller.js
  server/routes/reporting/some-report/some-report.controller.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
  server/routes/shared/complete-service/complete-service.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-272

#271 feature/JM-6470: Current pool status report
  client/templates/reporting/bureau-reports.njk
  client/templates/reporting/court-reports.njk
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-271

#281 hotfix/JM-7126 - Missing back link on Summons Reply page
  client/templates/response/detail.njk
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-281

#282 UAT - Numbers on assign reply screen and actual amount on officer to do is different
  server/routes/allocation/allocation.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-282

#279 Bug/JM-7128
  client/templates/response/_partials/notes.njk
  server/routes/juror-management/juror-record/index.js
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-279

#283 Hotfix/jm 6985
  client/templates/administration/court-details.njk
  client/templates/administration/expense-limits.njk
  client/templates/administration/users/create-users/user-details.njk
  client/templates/administration/users/edit-user.njk
  client/templates/administration/users/users.njk
  client/templates/custom-components/deferral-available-pools-week/template.njk
  client/templates/custom-components/super-navigation/super-navigation.njk
  client/templates/dashboard/deferral-excusal.njk
  client/templates/dashboard/index.njk
  client/templates/documents/_common/show-cause-form.njk
  client/templates/expenses/default-expenses.njk
  client/templates/expenses/enter-expenses-non-attendance.njk
  client/templates/expenses/enter-expenses.njk
  client/templates/includes/current_app.njk
  client/templates/juror-management/_errors/approval-denied.njk
  client/templates/juror-management/approve-expenses/approve-expenses.njk
  client/templates/juror-management/attendance.njk
  client/templates/juror-management/create-record-manual/ineligible-age.njk
  client/templates/juror-management/edit/juror-edit-details.njk
  client/templates/juror-management/manage-jurors.njk
  client/templates/juror-management/non-attendance-day.njk
  client/templates/juror-management/transfer-court.njk
  client/templates/juror-management/unpaid-attendance.njk
  client/templates/pool-management/_common/change-deferrals.njk
  client/templates/pool-management/movement/bulk-validate.njk
  client/templates/pool-management/request-pool/change-pool-number/index.njk
  client/templates/response/_edits/edit-eligibility.njk
  client/templates/response/_edits/edit-juror-details.njk
  client/templates/response/_modals/deferral.njk
  client/templates/response/call-log.njk
  client/templates/response/notes-edit.njk
  client/templates/response/process/deferral.njk
  client/templates/response/process/excusal.njk
  client/templates/staff/create.njk
  client/templates/staff/edit.njk
  client/templates/trial-management/empanel-jury/select-jurors.njk
  client/templates/trial-management/returns/confirm-return.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-283

#276 hotfix/JM-7129 - Bureau able to process a court-owned reply
  server/routes/summons-management/index.js
  server/routes/summons-management/process-reply/process-reply.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-276

#287 Feature/JM-6394: Panel Summary Report
  client/templates/trial-management/trial-detail.njk
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-287

#284 hotfix/JM-5614
  client/js/attendance.js
  client/templates/juror-management/attendance/unconfirmed/table-row.njk
  client/templates/juror-management/attendance/unconfirmed/unconfirmed.njk
  server/objects/index.js
  server/objects/police-check.js
  server/routes/juror-management/attendance/attendance.controller.js
  server/routes/juror-management/attendance/index.js
  server/routes/juror-management/police-check/juror-police-check.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-284

#291 hotfix/JM-7133
  client/templates/juror-management/juror-record/attendance.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-291

#280 hotfix/JM-7134
  client/templates/juror-management/_partials/juror-update-options.njk
  client/templates/juror-management/update-juror-record.njk
  server/routes/juror-management/juror-record/juror-record.controller.js
  server/routes/juror-management/update/juror-update.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-280

#288 hotfix/JM-7148
  server/routes/juror-management/update/index.js
  server/routes/juror-management/update/juror-update.disqualify.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-288

#294 Attendance letter says non-attendance even on attendance days
  server/routes/documents/print.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-294

#302 hotfix/JM-7033 -Incorrect date sorting on attendance table (Juror record)
  client/templates/juror-management/juror-record/_partials/attendance-table.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-302

#300 fix loc code for reports
  server/components/auth/index.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-300

#301 hotfix/JM-6795 - Error message required when setting next due at court date
  server/config/validation/change-attendance-date.js
  server/routes/pool-management/pool-overview/change-next-due-at-court/change-next-due-at-court.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-301

#305 Chore: Update standard report search validation
  server/config/validation/report-search-by.js
  server/routes/reporting/postponed-report/postponed.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-305

#307 hotfix/JM-7172: Update LocalDate handling for null report dates
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-307

#308 FE Implementation
  server/routes/search/search.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-308

#306 hotfix/JM-7153 - Missing 'Edit pool' button for Court users
  client/templates/pool-management/pool-overview/court-pool-overview.njk
  server/routes/pool-management/pool-overview/edit/edit-pool.controller.js
  server/routes/pool-management/pool-overview/pool-overview.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-306

#292 show urgent label for urgent and super urgent responses that are clos…
  client/templates/response/detail.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-292

#312 hotfix/JM-7179: Show hyphen if no data in reports
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-312

#311 Export details - data items all deselected by default
  client/templates/messaging/export-contact-details/details-to-export.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-311

#310 UAT - Notes and logs not working from summons reply
  client/templates/response/_partials/call-logs.njk
  client/templates/response/_partials/notes.njk
  client/templates/response/log.njk
  server/routes/juror-management/juror-record/index.js
  server/routes/juror-management/juror-record/juror-record.controller.js
  server/routes/summons-management/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-310

#314 Added aria-label to all links with link text 'Change' for accessibility
  client/templates/administration/users/create-users/confirm-details.njk
  client/templates/administration/users/edit-user.njk
  client/templates/documents/_common/letters-list.njk
  client/templates/documents/exemption/exemption-list.njk
  client/templates/expenses/bank-details.njk
  client/templates/expenses/travel-over-limit.njk
  client/templates/juror-management/attendance/unconfirmed/table-row.njk
  client/templates/juror-management/create-record-manual/summary.njk
  client/templates/juror-management/edit/juror-edit-details.njk
  client/templates/juror-management/juror-record/_partials/attendance-table.njk
  client/templates/juror-management/juror-record/attendance.njk
  client/templates/juror-management/juror-record/details.njk
  client/templates/juror-management/juror-record/expenses.njk
  client/templates/juror-management/juror-record/overview.njk
  client/templates/juror-management/reassign/pools.njk
  client/templates/messaging/_partials/juror-select-search.njk
  client/templates/pool-management/_common/change-attendance-date.njk
  client/templates/pool-management/_common/change-attendance-time.njk
  client/templates/pool-management/_common/check-request-details.njk
  client/templates/pool-management/additional-summons/index.njk
  client/templates/pool-management/convert-nil-pool/form.njk
  client/templates/pool-management/coroner-court/catchment-area.njk
  client/templates/pool-management/coroner-court/check-details.njk
  client/templates/pool-management/create-pool/summon-citizens/index.njk
  client/templates/pool-management/nil-pool/check-details.njk
  client/templates/pool-management/nil-pool/index.njk
  client/templates/pool-management/pool-create-manual/check-details.njk
  client/templates/pool-management/pool-create-manual/index.njk
  client/templates/pool-management/request-pool/change-pool-number/index.njk
  client/templates/pool-management/request-pool/pool-details/index.njk
  client/templates/response/_edits/edit-deferral-excusal.njk
  client/templates/response/_partials/cjs-employment.njk
  client/templates/response/_partials/deferral-excusal.njk
  client/templates/response/_partials/eligibility.njk
  client/templates/response/_partials/juror-details.njk
  client/templates/response/_partials/notes.njk
  client/templates/response/_partials/reasonable-adjustments.njk
  client/templates/sjo-tasks/uncomplete-service/select-jurors.njk
  client/templates/summons-management/_partials/signature.njk
  client/templates/summons-management/paper-reply/index.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-314

#315 Single juror record on search does not redirect to the juror record page
  client/templates/juror-management/search/index.njk
  server/routes/juror-management/search/search.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-315
