Repository hmcts/juror-bureau, pull requests merged in 2024-08, with the labels that each got.

#680 Court can not excuse a juror unless they have a response
  server/lib/mod-utils.js
  server/objects/excusal-mod.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-680

#679 hotfix/JM-7951: Redirect to summons reply on processing response
  client/templates/response/detail.njk
  server/routes/response/detail/detail.controller.js
  server/routes/summons-management/process-reply/disqualify/process-reply-disqualify.controller.js
  server/routes/summons-management/process-reply/reassign-before-process/reassign-before-process.controller.js
  server/routes/summons-management/summons-management.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-679

#669 Back button not working correctly across the application on certain screens
  client/templates/includes/back-link.njk
  client/templates/response/detail.njk
  client/templates/summons-management/excusal.njk
  server/config/express.js
  server/lib/back-link.js
  server/routes/juror-management/search/search.controller.js
  server/routes/response/detail/detail.controller.js
  server/routes/summons-management/summons-management.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-669

#683 Trial number with special character not allowing user to access
  server/components/filters/index.js
  server/config/validation/create-trial.js
  server/config/validation/messaging.js
  server/objects/create-trial.js
  server/objects/panel.js
  server/objects/return-jurors.js
  server/routes/messaging/export-contact-details.controller.js
  server/routes/messaging/send-messages.controller.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/trial-management/edit-trial/edit-trial.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-683

#684 Payment audit report - everyone still showing 1st January 2000 as the submitted date
  server/lib/reports/financial-audit.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-684

#681 Stabilisation8
  client/templates/response/detail.njk
  server/components/filters/index.js
  server/config/validation/create-trial.js
  server/config/validation/messaging.js
  server/lib/mod-utils.js
  server/lib/reports/financial-audit.js
  server/objects/create-trial.js
  server/objects/excusal-mod.js
  server/objects/panel.js
  server/objects/return-jurors.js
  server/routes/messaging/export-contact-details.controller.js
  server/routes/messaging/send-messages.controller.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/response/detail/detail.controller.js
  server/routes/summons-management/process-reply/disqualify/process-reply-disqualify.controller.js
  server/routes/summons-management/process-reply/reassign-before-process/reassign-before-process.controller.js
  server/routes/summons-management/summons-management.controller.js
  server/routes/trial-management/edit-trial/edit-trial.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-681

#686 As a court user I can not defer someone to the same day
  server/config/validation/date-picker.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-686

#692 Deferral Maintenance uses owner instead of locCode when returning deferred jurors
  server/routes/pool-management/deferral-maintenance/deferral-maintenance.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-692

#690 Back button not working correctly across the application on certain screens
  client/templates/includes/back-link.njk
  client/templates/response/detail.njk
  client/templates/summons-management/excusal.njk
  client/templates/summons-management/paper-reply/adjustments.njk
  client/templates/summons-management/paper-reply/cjs-employment.njk
  client/templates/summons-management/paper-reply/eligibility.njk
  client/templates/summons-management/paper-reply/reply-types.njk
  client/templates/summons-management/paper-reply/signature.njk
  server/config/express.js
  server/lib/back-link.js
  server/routes/juror-management/search/search.controller.js
  server/routes/response/detail/detail.controller.js
  server/routes/summons-management/summons-management.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-690

#693 INC2543730 - Value for "number of other jurors taken as passengers" goes missing when editing approved expenses
  server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-693

#698 Issue approving multiple juror's expenses
  server/routes/juror-management/approve-expenses/approve-expenses.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-698

#696 hotfix/JM-7991: Unpaid Attendance date filtering not working
  client/templates/juror-management/unpaid-attendance.njk
  server/routes/juror-management/unpaid-attendance/unpaid-attendance.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-696

#685 Hotfix/JM-7977: Update signature showing twice for certificate of attendance/exemption
  server/routes/documents/pdf/letter-generator.js
  server/routes/documents/pdf/letter-templates.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-685

#687 Error message is displayed wrong when checkout time < check in time
  server/routes/juror-management/attendance/attendance.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-687

#694 changes to catch termination
  Dockerfile
  server/app.js
  server/lib/appinsights.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-694

#697 Update expenses tables to not show the default date set (2000-01-01)
  client/templates/juror-management/_partials/attendance-tab.njk
  client/templates/juror-management/expense-record/_partials/approval-table.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-697

#677 Summons processed on date not correct on the summons reply view
  server/routes/summons-management/summons-management.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-677

#682 Trial links not rendering properly on juror-history
  server/components/filters/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-682

#700 Application crashes on trying to search for reports that need a date-range
  client/templates/reporting/standard-reports/date-search/fixed-range.njk
  server/config/validation/report-search-by.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-700

#701 Replace request-promise with axios on get expenses for approval and approving expenses
  server/objects/expenses.js
  server/routes/juror-management/approve-expenses/approve-expenses.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-701

#699 Stabilisation9
  Dockerfile
  client/templates/includes/back-link.njk
  client/templates/juror-management/_partials/attendance-tab.njk
  client/templates/juror-management/expense-record/_partials/approval-table.njk
  client/templates/juror-management/unpaid-attendance.njk
  client/templates/pool-management/_common/check-request-details.njk
  client/templates/reporting/standard-reports/date-search/fixed-range.njk
  client/templates/response/detail.njk
  client/templates/summons-management/excusal.njk
  client/templates/summons-management/paper-reply/adjustments.njk
  client/templates/summons-management/paper-reply/cjs-employment.njk
  client/templates/summons-management/paper-reply/eligibility.njk
  client/templates/summons-management/paper-reply/reply-types.njk
  client/templates/summons-management/paper-reply/signature.njk
  server/app.js
  server/components/filters/index.js
  server/config/express.js
  server/config/validation/date-picker.js
  server/config/validation/report-search-by.js
  server/lib/appinsights.js
  server/lib/back-link.js
  server/objects/expenses.js
  server/routes/documents/pdf/letter-generator.js
  server/routes/documents/pdf/letter-templates.js
  server/routes/juror-management/approve-expenses/approve-expenses.controller.js
  server/routes/juror-management/attendance/attendance.controller.js
  server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
  server/routes/juror-management/search/search.controller.js
  server/routes/juror-management/unpaid-attendance/unpaid-attendance.controller.js
  server/routes/pool-management/deferral-maintenance/deferral-maintenance.controller.js
  server/routes/pool-management/request-pool/request-pool.controller.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/response/detail/detail.controller.js
  server/routes/summons-management/summons-management.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-699

#703 Certificate of Attendance - "Sorry there has been a technical problem" when tying to print the certificate.
  server/components/filters/index.js
  server/routes/documents/pdf/letter-generator.js
  server/routes/documents/print.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-703

#702 Trial number with '/' not allowing user to access
  client/templates/juror-management/_partials/attendance-tab.njk
  server/config/validation/messaging.js
  server/lib/mod-utils.js
  server/routes/trial-management/trial-management.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-702

#691 Trial attendance report not showing inactive trials.
  client/templates/reporting/standard-reports/trial-select.njk
  client/templates/trial-management/trial-detail.njk
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-691

#706 hotfix/JM-8020: Replace Request-Promise with Axios - Submit Draft Expenses & Editing Expenses
  server/objects/expense-record.js
  server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/draft.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-706

#708 App crashes on `travel over limit` if the user goes back with browser arrows
  server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/expense-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-708

#709 Update api DAO for juror-search on messages journeys
  server/objects/messaging.js
  server/routes/messaging/export-contact-details.controller.js
  server/routes/messaging/send-messages.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-709

#713 INC2554492 - Trial numbers incomplete or missing on Juror history
  server/components/filters/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-713

#714 Warning icon missing from records that should display
  client/templates/summons-management/_common/details-banner-new.njk
  server/routes/juror-management/juror-record/juror-record.controller.js
  webpack/htmlWebpack.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-714

#712 hotfix/JM-8031: Fix travel expenses duplication
  server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
  server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-712

#716 Confirming a trial attendance can override an existing confirmed attendance
  server/routes/juror-management/jurors-on-trial/jurors-on-trial.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-716

#718 update summons update to work with multiple tabs
  client/js/multiple-tabs.js
  server/routes/summons-management/summons-management.controller.js
  server/routes/summons-management/update/cjs-employment.controller.js
  server/routes/summons-management/update/eligibility.controller.js
  server/routes/summons-management/update/juror-details.controller.js
  server/routes/summons-management/update/reasonable-adjustments.controller.js
  server/routes/summons-management/update/reply-type.controller.js
  server/routes/summons-management/update/signature.controller.js
  server/routes/summons-management/update/summons-update-common.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-718

#717 Update trial-management flows to restrict multi-tab data issues
  server/routes/pool-management/pool-overview/pool-overview.controller.js
  server/routes/trial-management/add-panel-members/add-panel-member.controller.js
  server/routes/trial-management/create-trial/create-trial.controller.js
  server/routes/trial-management/edit-trial/edit-trial.controller.js
  server/routes/trial-management/empanel-jury/empanel-jury.controller.js
  server/routes/trial-management/generate-panel/generate-panel.controller.js
  server/routes/trial-management/returns.controller.js
  server/routes/trial-management/trial-management.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-717

#707 Multiple tabs open are causing data issues
  client/js/multiple-tabs.js
  client/scss/mod-custom.scss
  client/templates/_errors/data-mismatch.njk
  client/templates/includes/scripts.njk
  client/templates/layouts/govuk_template.njk
  client/templates/pool-management/create-pool/summon-citizens/index.njk
  client/templates/pool-management/delete-pool/confirm.njk
  client/templates/pool-management/pool-overview/bureau-pool-overview.njk
  server/components/auth/index.js
  server/objects/delete-pool.js
  server/objects/delete-pool.spec.js
  server/objects/pool-summary.js
  server/objects/pool-summary.spec.js
  server/objects/summons-form.js
  server/routes/index.js
  server/routes/juror-management/create-record-manual/create-record-manual.controller.js
  server/routes/juror-management/edit/juror-edit.controller.js
  server/routes/juror-management/juror-record/juror-record.controller.js
  server/routes/pool-management/additional-summons/additional-summons.controller.js
  server/routes/pool-management/create-pool/summon-citizens/summon-citizens.controller.js
  server/routes/pool-management/delete-pool/delete-pool.controller.js
  server/routes/pool-management/delete-pool/index.js
  server/routes/pool-management/pool-overview/bureau-view.js
  server/routes/pool-management/pool-overview/edit/edit-pool.controller.js
  server/routes/pool-management/pool-overview/pool-overview.controller.js
  server/routes/summons-management/summons-management.controller.js
  server/routes/summons-management/update/cjs-employment.controller.js
  server/routes/summons-management/update/eligibility.controller.js
  server/routes/summons-management/update/juror-details.controller.js
  server/routes/summons-management/update/reasonable-adjustments.controller.js
  server/routes/summons-management/update/reply-type.controller.js
  server/routes/summons-management/update/signature.controller.js
  server/routes/summons-management/update/summons-update-common.js
  server/routes/trial-management/add-panel-members/add-panel-member.controller.js
  server/routes/trial-management/create-trial/create-trial.controller.js
  server/routes/trial-management/edit-trial/edit-trial.controller.js
  server/routes/trial-management/empanel-jury/empanel-jury.controller.js
  server/routes/trial-management/generate-panel/generate-panel.controller.js
  server/routes/trial-management/returns.controller.js
  server/routes/trial-management/trial-management.controller.js
  webpack/htmlWebpack.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-707

#729 update the multiple tabs script to only be served for signed in people
  client/templates/includes/scripts.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-729

#726 fix crash on trying to post non-edited expenses
  server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-726

#728 fix pnc try-again links on the juror-overview page
  client/templates/juror-management/juror-record/overview.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-728

#719 Letters have too much space between "Yours sincerely," and the signature
  server/routes/documents/pdf/letter-generator.js
  server/routes/documents/pdf/letter-templates.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-719

#734 Saving juror bank details causing a 500 internal service error
  server/routes/juror-management/edit/juror-edit.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-734

#715 Stabilisation 11
  client/js/multiple-tabs.js
  client/scss/mod-custom.scss
  client/templates/_errors/data-mismatch.njk
  client/templates/includes/scripts.njk
  client/templates/juror-management/juror-record/overview.njk
  client/templates/layouts/govuk_template.njk
  client/templates/pool-management/create-pool/summon-citizens/index.njk
  client/templates/pool-management/deferral-maintenance/_partials/filters.njk
  client/templates/pool-management/deferral-maintenance/index.njk
  client/templates/pool-management/delete-pool/confirm.njk
  client/templates/pool-management/pool-overview/bureau-pool-overview.njk
  client/templates/summons-management/_common/details-banner-new.njk
  package.json
  server/components/auth/index.js
  server/components/filters/index.js
  server/objects/delete-pool.js
  server/objects/delete-pool.spec.js
  server/objects/pool-summary.js
  server/objects/pool-summary.spec.js
  server/objects/summons-form.js
  server/routes/documents/letters-list/letters-list.controller.js
  server/routes/documents/pdf/letter-generator.js
  server/routes/documents/pdf/letter-templates.js
  server/routes/index.js
  server/routes/juror-management/create-record-manual/create-record-manual.controller.js
  server/routes/juror-management/edit/juror-edit.controller.js
  server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
  server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js
  server/routes/juror-management/juror-record/juror-record.controller.js
  server/routes/juror-management/jurors-on-trial/jurors-on-trial.controller.js
  server/routes/juror-management/update/juror-update.transfer.controller.js
  server/routes/pool-management/additional-summons/additional-summons.controller.js
  server/routes/pool-management/create-pool/summon-citizens/summon-citizens.controller.js
  server/routes/pool-management/deferral-maintenance/deferral-maintenance.controller.js
  server/routes/pool-management/deferral-maintenance/index.js
  server/routes/pool-management/delete-pool/delete-pool.controller.js
  server/routes/pool-management/delete-pool/index.js
  server/routes/pool-management/pool-overview/bureau-view.js
  server/routes/pool-management/pool-overview/edit/edit-pool.controller.js
  server/routes/pool-management/pool-overview/pool-overview.controller.js
  server/routes/summons-management/summons-management.controller.js
  server/routes/summons-management/update/cjs-employment.controller.js
  server/routes/summons-management/update/eligibility.controller.js
  server/routes/summons-management/update/juror-details.controller.js
  server/routes/summons-management/update/reasonable-adjustments.controller.js
  server/routes/summons-management/update/reply-type.controller.js
  server/routes/summons-management/update/signature.controller.js
  server/routes/summons-management/update/summons-update-common.js
  server/routes/trial-management/add-panel-members/add-panel-member.controller.js
  server/routes/trial-management/create-trial/create-trial.controller.js
  server/routes/trial-management/edit-trial/edit-trial.controller.js
  server/routes/trial-management/empanel-jury/empanel-jury.controller.js
  server/routes/trial-management/generate-panel/generate-panel.controller.js
  server/routes/trial-management/returns.controller.js
  server/routes/trial-management/trial-management.controller.js
  webpack/htmlWebpack.js
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-715

#732 Hide the "next due at court date" for deferred jurors to aviod confusion with this date.
  client/templates/juror-management/_partials/heading.njk
  client/templates/juror-management/juror-record/attendance.njk
  client/templates/juror-management/juror-record/overview.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-732

#730 Third party details in the juror record does not save the details
  client/templates/juror-management/_partials/third-party-details.njk
  client/templates/juror-management/edit/juror-edit-details.njk
  server/config/validation/edit-juror-details-mod.js
  server/objects/juror-record.js
  server/routes/juror-management/edit/juror-edit.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-730

#723 add timezone formats for the report times (possible fix)
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-723

#733 Returning a jury without check out time can leave jurors in limbo
  client/templates/juror-management/attendance.njk
  client/templates/trial-management/returns/return-attendance.njk
  server/routes/juror-management/juror-management.controller.js
  server/routes/trial-management/returns.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-733

#736 Digital - Assign Replies - Total is at the bottom. This has not matched where it was located in heritage (Juror digital)
  client/templates/allocation/index.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-736

#741 Hide "Expenses approval limits" for Court Managers and SJO's
  client/templates/administration/users/create-users/confirm-details.njk
  client/templates/administration/users/create-users/user-details.njk
  client/templates/administration/users/edit-user.njk
  server/config/validation/create-users.js
  server/routes/administration/users/create-users/create-users.controller.js
  server/routes/administration/users/edit-user/edit-user.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-741

#740 Unable to update juror-details if they are disqualified by age
  server/routes/juror-management/edit/juror-edit.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-740

#742 Bureau unable to summon additional jurors to pools. "Something has changed since last viewed" error message is appearing.
  client/templates/pool-management/additional-summons/index.njk
  client/templates/pool-management/create-pool/summon-citizens/index.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-742

#739 hotfix/JM-8082: Edit user button not showing in "Court Administration" section of the application
  client/templates/administration/users/user-record.njk
  server/routes/administration/users/edit-user/edit-user.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-739

#743 Disqualifying juror by age on editing the juror details does not save the date-of-birth
  server/routes/juror-management/edit/juror-edit.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-743

#737 hotfix/JM-8077: Deferral Maintenance Screen Not Sorting on Pagination
  client/templates/pool-management/deferral-maintenance/_partials/deferrals-table.njk
  server/routes/pool-management/deferral-maintenance/deferral-maintenance.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-737

#744 Jury officer has no space for signing letters
  server/routes/documents/pdf/letter-generator.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-744

#746 Rename Juror Details pop-out save buttons to be "Review Edit"
  client/templates/summons-management/paper-reply/edit-address.njk
  client/templates/summons-management/paper-reply/edit-name.njk
  server/routes/juror-management/edit/juror-edit.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-746

#745 Third party details in the juror record does not save the details
  client/templates/juror-management/_partials/third-party-details.njk
  client/templates/response/_partials/juror-details.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-745

#731 add a way to sort printable reports
  client/js/print-sortable.js
  client/templates/reporting/standard-reports/grouped-table.njk
  client/templates/reporting/standard-reports/standard-report.njk
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
  webpack/htmlWebpack.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-731

#747 hotfix/JM-8098: Flag marked showing incorrectly on straight through responses and reasonable adjustment responses.
  client/templates/summons-management/_common/details-banner-new.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-747

#752 update button label on edit address when submitting paper-reply
  server/routes/summons-management/paper-reply/paper-reply.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-752

#738 Stabilisation12
  client/js/print-sortable.js
  client/templates/administration/users/create-users/confirm-details.njk
  client/templates/administration/users/create-users/user-details.njk
  client/templates/administration/users/edit-user.njk
  client/templates/administration/users/user-record.njk
  client/templates/allocation/index.njk
  client/templates/juror-management/_partials/heading.njk
  client/templates/juror-management/_partials/third-party-details.njk
  client/templates/juror-management/attendance.njk
  client/templates/juror-management/edit/juror-edit-details.njk
  client/templates/juror-management/juror-record/attendance.njk
  client/templates/juror-management/juror-record/overview.njk
  client/templates/pool-management/additional-summons/index.njk
  client/templates/pool-management/create-pool/summon-citizens/index.njk
  client/templates/pool-management/deferral-maintenance/_partials/deferrals-table.njk
  client/templates/reporting/standard-reports/grouped-table.njk
  client/templates/reporting/standard-reports/standard-report.njk
  client/templates/response/_partials/juror-details.njk
  client/templates/summons-management/_common/details-banner-new.njk
  client/templates/summons-management/paper-reply/edit-address.njk
  client/templates/summons-management/paper-reply/edit-name.njk
  client/templates/trial-management/returns/return-attendance.njk
  server/config/validation/create-users.js
  server/config/validation/edit-juror-details-mod.js
  server/objects/juror-record.js
  server/routes/administration/users/create-users/create-users.controller.js
  server/routes/administration/users/edit-user/edit-user.controller.js
  server/routes/documents/pdf/letter-generator.js
  server/routes/juror-management/edit/juror-edit.controller.js
  server/routes/juror-management/juror-management.controller.js
  server/routes/pool-management/deferral-maintenance/deferral-maintenance.controller.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
  server/routes/response/detail/detail.controller.js
  server/routes/summons-management/paper-reply/paper-reply.controller.js
  server/routes/summons-management/update/juror-details.controller.js
  server/routes/trial-management/returns.controller.js
  webpack/htmlWebpack.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-738

#754 Attendance and payment history shows incorrect data
  client/templates/juror-management/_partials/attendance-tab.njk
  server/components/filters/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-754

#753 make pool-ratio report sortable
  server/routes/reporting/standard-report/definitions.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-753

#751 update trial links to use the original name as it is used to link gen
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-751

#750 Custom column sizes for pool-attendance audit
  server/routes/reporting/standard-report/definitions.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-750

#757 hotfix/JM-8117: Summons Response advance search on AUTO + Completed fails
  client/templates/search/index.njk
  server/routes/search/search.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-757

#760 Pool ratio report should be sortable
  server/routes/reporting/standard-report/standard-report-print.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-760

#759 Filtering on service start date on active pool screen only applies to page you filter on
  server/lib/mod-utils.js
  server/objects/pool-list.js
  server/routes/pool-management/pool-management.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-759

#764 The persons attending details and summery to add an option to include panel/juror status jurors
  client/templates/reporting/persons-attending/attendance-date.njk
  server/routes/reporting/persons-attending/persons-attending-controller.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-764

#756 hotfix/JM-8111: Internal server error when clicking Back link after age disqualification
  server/lib/back-link.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-756

#767 Permission change to allow the Bureau general users to edit change name / fix error in name option
  client/templates/juror-management/edit/juror-edit-details.njk
  client/templates/summons-management/paper-reply/index.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-767

#768 Attendance ordering incorrect on juror history
  client/templates/juror-management/_partials/attendance-tab.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-768

#766 The "Print List" button on the trials list page does nothing
  client/templates/trial-management/trials.njk
  server/lib/reports/single-generator.js
  server/routes/trial-management/index.js
  server/routes/trial-management/trial-management.print.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-766

#769 INC2553487 - Bureau asked re-assign to another court after deferring any a juror
  server/routes/response/detail/detail.controller.js
  server/routes/summons-management/process-reply/process-reply.controller.js
  server/routes/summons-management/process-reply/reassign-before-process/reassign-before-process.controller.js
  server/routes/summons-management/summons-management.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-769

#761 Sorting on dismiss-jurors list sorts only the current page
  client/templates/juror-management/dismiss-jurors/jurors-table.njk
  server/routes/juror-management/dismiss-jurors/dismiss-jurors.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-761

#765 hotfix/JM-7949: A juror with a juror_pool status of 2 and response in TODO tries to call a removed endpoint
  server/routes/response/detail/detail.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-765

#758 Stabilisation13
  client/templates/juror-management/_partials/attendance-tab.njk
  client/templates/juror-management/dismiss-jurors/jurors-table.njk
  client/templates/juror-management/edit/juror-edit-details.njk
  client/templates/messaging/_partials/juror-list-results.njk
  client/templates/messaging/export-contact-details/jurors-list.njk
  client/templates/reporting/persons-attending/attendance-date.njk
  client/templates/search/index.njk
  client/templates/summons-management/paper-reply/index.njk
  client/templates/trial-management/trials.njk
  server/components/filters/index.js
  server/lib/back-link.js
  server/lib/mod-utils.js
  server/lib/reports/ballot.js
  server/lib/reports/single-generator.js
  server/objects/pool-list.js
  server/routes/juror-management/dismiss-jurors/dismiss-jurors.controller.js
  server/routes/messaging/export-contact-details.controller.js
  server/routes/pool-management/pool-management.controller.js
  server/routes/reporting/persons-attending/persons-attending-controller.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
  server/routes/response/detail/detail.controller.js
  server/routes/search/search.controller.js
  server/routes/summons-management/process-reply/process-reply.controller.js
  server/routes/summons-management/process-reply/reassign-before-process/reassign-before-process.controller.js
  server/routes/summons-management/summons-management.controller.js
  server/routes/trial-management/index.js
  server/routes/trial-management/trial-management.print.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-758
