Repository hmcts/juror-bureau, pull requests merged in 2024-05, with the labels that each got.

#316 fix a missing comma on a nunjucks macro
  client/templates/administration/users/create-users/confirm-details.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-316

#317 Unable to manually create a juror
  client/templates/juror-management/create-record-manual/juror-contact.njk
  client/templates/juror-management/create-record-manual/notes.njk
  server/config/validation/record-create-manual.js
  server/lib/mod-utils.js
  server/routes/juror-management/create-record-manual/create-record-manual.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-317

#318 hotfix/JM-6350 - Error when fixing current name and entering a new name
  server/routes/juror-management/edit/juror-edit.controller.js
  server/routes/summons-management/paper-reply/paper-reply.controller.js
  server/routes/summons-management/update/juror-details.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-318

#319 Last Login Date incorrectly displayed on System Admin > Users screen
  server/routes/administration/users/users.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-319

#321 hotfix/JM-7159 - Wrong input validation
  server/config/validation/document-form.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-321

#322 task/JM-7188: Standardised Reports Court Select Screen
  client/scss/mod-custom.scss
  client/templates/reporting/standard-reports/court-select.njk
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-322

#324 Hotfix/jm 6989
  client/templates/administration/courts-and-bureau.njk
  client/templates/response/_partials/cjs-employment.njk
  client/templates/response/_partials/deferral-excusal.njk
  client/templates/response/_partials/eligibility.njk
  client/templates/response/_partials/juror-details.njk
  client/templates/response/_partials/reasonable-adjustments.njk
  client/templates/sjo-tasks/uncomplete-service/select-jurors.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-324

#297 Feature/JM-5911: Bulk-Print Audit Report (Abaccus Report)
  client/templates/reporting/bureau-reports.njk
  client/templates/reporting/standard-reports/date-search.njk
  server/config/validation/report-search-by.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-297

#326 Update pool-management.js
  server/objects/pool-management.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-326

#328 Hotfix/jm 6993
  client/templates/administration/users/assign-courts/assign-courts.njk
  client/templates/pool-management/index.njk
  client/templates/reporting/standard-reports/court-select.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-328

#327 JM-7215 - Reasonable adjustments display for digital repsonse
  client/templates/response/_partials/reasonable-adjustments.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-327

#298 feature/JM-6396: Trial Detail Report
  client/templates/trial-management/trial-detail.njk
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-298

#329 Login to Azure - As a user I need to be able to sign in to the system (FE)
  client/templates/layouts/govuk_template.njk
  client/templates/sign-in.njk
  config/environment.template.json
  server/lib/session-config.js
  server/routes/authentication/azure.controller.js
  server/routes/authentication/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-329

#299 feature/JM-6402: Jury List Report
  client/templates/trial-management/trial-detail.njk
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-299

#331 JM-7151: It is possible to mark a juror as responded without a DOB
  server/routes/juror-management/update/juror-update.responded.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-331

#332 feature/JM-6379: Incomplete Service Report
  client/templates/reporting/standard-reports/standard-report.njk
  client/templates/shared/complete-service/complete-service-confirm.njk
  server/routes/reporting/incomplete-service/incomplete-service.controller.js
  server/routes/reporting/incomplete-service/index.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/shared/complete-service/complete-service.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-332

#340 Update README.md
  README.md
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-340

#333 hotfix/JM-7047 - Edit pool on pool requests for Bureau users
  client/templates/pool-management/pool-overview/bureau-pool-overview.njk
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-333

#334 hotfix/JM-7123 - Existing email FE error handling
  client/templates/administration/users/create-users/confirm-details.njk
  server/routes/administration/users/create-users/create-users.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-334

#335 hotfix/JM-7214 - 'Summoned' jurors should not have their next due changed (Juror record).
  client/templates/juror-management/juror-record/attendance.njk
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-335

#337 hotfix/JM-7165 - Sending juror messages causing technical error
  server/routes/messaging/send-messages.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-337

#338 hotfix/JM-7200 - satellite courts appearing when assigning courts to users (Admin user)
  server/routes/administration/users/assign-courts/assign-courts.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-338

#336 2 links with text "Advanced search" on search page
  client/templates/custom-components/super-navigation/super-navigation.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-336

#330 Internal server error where juror's postcode exists in >1 court_catchment_area
  client/templates/response/_partials/call-logs.njk
  client/templates/response/_partials/notes.njk
  client/templates/summons-management/_partials/signature.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-330

#341 Granting or refusing deferral requests as a Bureau user is failing
  server/config/validation/deferral-mod.js
  server/routes/juror-management/update/juror-update.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-341

#323 Bug/JM-6931 - Pool overview (as a bureau officer) nothing happens when I click All Jurors
  client/js/pool-overview.js
  client/templates/pool-management/pool-overview/_partials/filters.njk
  client/templates/pool-management/pool-overview/bureau-pool-jurors.njk
  client/templates/pool-management/pool-overview/court-pool-jurors.njk
  server/objects/index.js
  server/objects/pool-members.js
  server/routes/pool-management/pool-overview/bureau-view.js
  server/routes/pool-management/pool-overview/change-next-due-at-court/change-next-due-at-court.controller.js
  server/routes/pool-management/pool-overview/paginate-jurors-list.js
  server/routes/pool-management/pool-overview/pool-overview.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-323

#342 Attendance details on unpaid attendance incorrect after returning jury
  client/templates/juror-management/expense-record/_partials/expenses-table-macros.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-342

#343 fix the summons details page
  client/templates/response/_partials/juror-details.njk
  client/templates/response/detail.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-343

#344 Summons Reply - Juror details Email field doesn't have the same structure
  client/templates/response/_partials/juror-details.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-344

#345 As a FE dev I want to update inline js events to be set on script tags for security enforcement
  client/templates/administration/judges/judges.njk
  client/templates/administration/users/assign-courts/_partials/assign-courts-table.njk
  client/templates/administration/users/assign-courts/assign-courts.njk
  client/templates/administration/users/court-bureau-users.njk
  client/templates/administration/users/users.njk
  client/templates/juror-management/approve-expenses/_partials/approve-expenses-table.njk
  client/templates/juror-management/approve-expenses/approve-expenses.njk
  client/templates/juror-management/manage-jurors/approve-jurors.njk
  client/templates/juror-management/reassign/pools.njk
  client/templates/pool-management/deferral-maintenance/_partials/pools-table.njk
  client/templates/reporting/some-report/index.njk
  client/templates/reporting/standard-reports/court-select.njk
  client/templates/trial-management/_partials/trial-panel.njk
  client/templates/trial-management/trials.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-345

#347 ID on reasonable adjustments is "disability"
  client/templates/response/_partials/reasonable-adjustments.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-347

#346 feature/JM-5908: Pool Status Report
  client/scss/mod-custom.scss
  client/templates/reporting/bureau-reports.njk
  client/templates/reporting/court-reports.njk
  client/templates/reporting/standard-reports/bespoke-report-body/pool-status.njk
  client/templates/reporting/standard-reports/standard-report.njk
  server/lib/reports/single-generator.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/report-export.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-346

#348 Attendance letter says non-attendance even on attendance days
  server/lib/mod-utils.js
  server/routes/documents/print.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-348

#352 hotfix/JM-7219 - Time created incorrect on reports
  server/routes/reporting/standard-report/utils.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-352

#351 hotfix/JM-7205 - Bureau user (non-manager) can assign response to another user
  client/templates/response/_partials/update-header.njk
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-351

#355 hotfix/JM-7277 - End trial date can be set before trial start date
  server/config/validation/end-trial.js
  server/config/validation/end-trial.spec.js
  server/routes/trial-management/trial-management.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-355

#357 Bug (JM-7283) add audit number to footer
  server/lib/reports/financial-audit.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-357

#350 As a jury/bureau officer I wan to generate a special needs (Reasonable adjustment) report (FE)
  client/templates/reporting/bureau-reports.njk
  client/templates/reporting/court-reports.njk
  client/templates/reporting/standard-reports/date-search.njk
  client/templates/reporting/standard-reports/date-search/fixed-range.njk
  client/templates/reporting/standard-reports/date-search/from-to.njk
  server/config/validation/report-search-by.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-350

#358 make the pool number in reports be a clickable link
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-358

#359 hotfix/JM-7270 - Bulk postponing a pool with causes unhandled error screen
  server/routes/pool-management/pool-overview/change-next-due-at-court/change-next-due-at-court.controller.js
  server/routes/pool-management/pool-overview/pool-overview.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-359

#360 hotfix/JM-7266 - Non Responded List - Bureau owned pools outputting technical error
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-360

#365 Improve the performance of the "Your Work" pages
  server/objects/responses.js
  server/routes/completed/completed.controller.js
  server/routes/completed/index.js
  server/routes/inbox/inbox.controller.js
  server/routes/inbox/index.js
  server/routes/pending/index.js
  server/routes/pending/pending.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-365

#364 Chore/font size
  server/lib/reports/default-layout.js
  server/lib/reports/financial-audit.js
  server/lib/reports/single-generator.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-364

#356 feature/JM-6480: Daily Utilisation Report
  client/scss/mod-custom.scss
  client/templates/reporting/court-statistics.njk
  client/templates/reporting/daily-utilisation/uncompleted-jurors.njk
  client/templates/reporting/standard-reports/standard-report.njk
  server/config/validation/report-search-by.js
  server/objects/reports.js
  server/routes/reporting/bespoke-report/bespoke-report-body.js
  server/routes/reporting/bespoke-report/bespoke-report-print.js
  server/routes/reporting/daily-utilisation/daily-utilisation.controller.js
  server/routes/reporting/daily-utilisation/index.js
  server/routes/reporting/reporting.controller.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/report-export.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-356

#354 Feature/JM-6408: Panel Ballot report
  client/templates/pool-management/pool-overview/court-pool-overview.njk
  server/lib/reports/ballot.js
  server/routes/juror-management/juror-record/juror-record.controller.js
  server/routes/pool-management/pool-overview/index.js
  server/routes/pool-management/pool-overview/pool-overview.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-354

#367 hotfix/Jm-6480: Add date range length validation to daily utilisation
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-367

#366 ITHC - Lack Of Anti-Automation Protections
  charts/juror-bureau/Chart.yaml
  charts/juror-bureau/values.yaml
  package.json
  server/config/environment/index.js
  server/config/express.js
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-366

#371 Non-Bureau users can not reassign jurors
  client/templates/juror-management/_partials/juror-update-options.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-371

#370 Pagination buttons don't work in active pool
  client/templates/pool-management/pool-overview/bureau-pool-jurors.njk
  client/templates/pool-management/pool-overview/bureau-pool-overview.njk
  client/templates/pool-management/pool-overview/court-pool-jurors.njk
  client/templates/pool-management/pool-overview/court-pool-overview.njk
  server/routes/pool-management/pool-overview/bureau-view.js
  server/routes/pool-management/pool-overview/pool-overview.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-370

#379 Hotfix/jm 7299
  client/templates/pool-management/coroner-court/catchment-area.njk
  server/routes/pool-management/pool-overview/paginate-jurors-list.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-379

#369 hotfix/JM-7249 - UAT - No select all button at the top of letters for Bureau
  client/js/document-letters.js
  client/templates/documents/_common/letters-list.njk
  server/routes/documents/helper/table-generator.js
  server/routes/documents/letters-list/letters-list.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-369

#381 Attendance letter says non-attendance even on attendance days
  server/routes/documents/print.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-381

#385 deps/remove-open-ip
  package.json
  server/components/logger/juror-transport.js
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-385

#388 update eslint to latest and ignore everything
  .eslintignore
  .eslintrc
  eslint.config.js
  package.json
  server/app.js
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-388

#389 update lodash
  package.json
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-389

#390 remove eslint plugins
  package.json
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-390

#361 As a jury officer I want to generate an unconfirmed /unpaid attendance report (FE)
  client/scss/mod-custom.scss
  client/templates/reporting/bureau-reports.njk
  client/templates/reporting/court-reports.njk
  client/templates/reporting/court-statistics.njk
  server/components/filters/index.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-361

#384 Improve performance of the expense flow
  server/lib/mod-utils.js
  server/objects/expenses.js
  server/routes/juror-management/unpaid-attendance/unpaid-attendance.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-384

#391 update page titles on reports pages
  client/templates/reporting/daily-utilisation/uncompleted-jurors.njk
  client/templates/reporting/incomplete-service/cutoff-date.njk
  client/templates/reporting/persons-attending/attendance-date.njk
  client/templates/reporting/standard-reports/court-select.njk
  client/templates/reporting/standard-reports/date-search.njk
  client/templates/reporting/standard-reports/pool-search.njk
  client/templates/reporting/standard-reports/standard-report.njk
  server/lib/mod-utils.js
  server/routes/juror-management/unpaid-attendance/unpaid-attendance.controller.js
  server/routes/reporting/daily-utilisation/daily-utilisation.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-391

#392 undefined deferral reasons on juror update
  server/routes/juror-management/update/juror-update.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-392

#400 Hotfix/jm 6993
  client/templates/inbox.njk
  client/templates/juror-management/attendance/check-out-panelled.njk
  client/templates/response/detail.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-400

#401 When entering draft expenses and clicking save and back an invalid payload is set to the BE code which leads to a 400 being returned
  server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-401

#402 Fixed issue with utilisation report first time render
  server/routes/reporting/standard-report/definitions.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-402

#404 fix/missing-tableDataMappers
  server/routes/reporting/bespoke-report/bespoke-report-body.js
  server/routes/reporting/bespoke-report/bespoke-report-print.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-404

#380 As a court officer I want to generate a Panel member status report (FE)
  client/scss/mod-custom.scss
  client/templates/reporting/standard-reports/standard-report.njk
  client/templates/trial-management/trial-detail.njk
  server/lib/reports/default-layout.js
  server/lib/reports/single-generator.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-380

#407 Hotfix/jm 7299
  client/templates/allocation/index.njk
  client/templates/messaging/export-contact-details/jurors-table.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-407

#362 feature/JM-6482&6484: Monthly Utilisation Report
  client/templates/reporting/court-statistics.njk
  client/templates/reporting/monthly-utilisation/confirm-prepare.njk
  client/templates/reporting/monthly-utilisation/prepare-select-month.njk
  client/templates/reporting/monthly-utilisation/view-select-month.njk
  client/templates/reporting/standard-reports/standard-report.njk
  server/objects/reports.js
  server/routes/reporting/bespoke-report/bespoke-report-body.js
  server/routes/reporting/bespoke-report/bespoke-report-print.js
  server/routes/reporting/monthly-utilisation/index.js
  server/routes/reporting/monthly-utilisation/monthly-utilisation.controller.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/report-export.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-362

#403 Fix/remove unnecessary response call
  server/routes/juror-management/juror-record/index.js
  server/routes/juror-management/juror-record/juror-record.controller.js
  server/routes/summons-management/paper-reply/index.js
  server/routes/summons-management/paper-reply/paper-reply.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-403

#410 fix/JM-7327: panel members status report
  server/routes/reporting/standard-report/definitions.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-410

#409 feature/JM-6472&6474&6476: Jury Expenditure Reports
  client/scss/mod-custom.scss
  client/templates/reporting/court-statistics.njk
  client/templates/reporting/standard-reports/bespoke-report-body/pool-status.njk
  client/templates/reporting/standard-reports/date-search/from-to.njk
  client/templates/reporting/standard-reports/standard-report.njk
  server/components/filters/index.js
  server/lib/mod-utils.js
  server/lib/reports/default-layout.js
  server/lib/reports/financial-audit.js
  server/routes/reporting/bespoke-report/bespoke-report-body.js
  server/routes/reporting/bespoke-report/bespoke-report-print.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-409

#412 Non-Bureau users can not reassign jurors
  client/templates/juror-management/_partials/juror-update-options.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-412

#411 feature/JM-6366: Absences Report
  client/templates/reporting/court-reports.njk
  server/config/validation/report-search-by.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-411

#415 Hotfix/jm 7299
  client/templates/administration/system-codes.njk
  client/templates/reporting/bureau-reports.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-415

#363 JM-7256: Internal server error when selecting juror number link from appearance table
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-363

#419 Hotfix/jm 7099
  client/scss/mod-custom.scss
  client/templates/administration/courts-and-bureau.njk
Labels: ns:juror, prd:juror

#417 feature/JM-6410: Jury Summary Report (Trial Statistics)
  client/templates/reporting/court-statistics.njk
  client/templates/reporting/standard-reports/standard-report.njk
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-417

#416 feature/JM-6414: Available List reports
  client/templates/reporting/available-list/search-by.njk
  client/templates/reporting/bureau-reports.njk
  client/templates/reporting/court-reports.njk
  server/config/validation/report-search-by.js
  server/routes/reporting/available-list/available-list.controller.js
  server/routes/reporting/available-list/index.js
  server/routes/reporting/index.js
  server/routes/reporting/persons-attending/persons-attending-controller.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-416

#267 Azure AD auth flow
  README.md
  charts/juror-bureau/Chart.yaml
  charts/juror-bureau/values.dev.template.yaml
  charts/juror-bureau/values.stg.template.yaml
  charts/juror-bureau/values.yaml
  client/scss/custom-components/_super-navigation.scss
  client/scss/mod-custom.scss
  client/templates/administration/courts-and-bureau.njk
  client/templates/authentication/courts-list.njk
  client/templates/custom-components/super-navigation/change-court.njk
  client/templates/layouts/govuk_template.njk
  client/templates/sign-in.njk
  config/environment.template.json
  server/components/auth/auth.spec.js
  server/components/auth/index.js
  server/components/auth/user-type.js
  server/config/environment/index.js
  server/config/express.js
  server/lib/session-config.js
  server/objects/axios-instance.js
  server/routes/authentication/authentication.controller.js
  server/routes/authentication/azure.controller.js
  server/routes/authentication/index.js
  server/routes/index.js
  server/routes/login/index.js
  server/routes/login/login.controller.js
Labels: enhancement, ns:juror, prd:juror, rel:juror-bureau-pr-267, enable_keep_helm

#414 Replace grunt with webpack
  README.md
  client/js/main.js
  client/templates/includes/head.njk
  eslint.config.js
  eslint.unignore.js
  nodemon.json
  package.json
  server/config/express.js
  webpack.config.js
  webpack/htmlWebpack.js
  webpack/scss.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-414

#425 remove the gruntfile
  Gruntfile.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-425

#432 task/JM-7437: Update to use new trials list endpoint
  server/lib/mod-utils.js
  server/objects/create-trial.js
  server/objects/create-trial.spec.js
  server/routes/messaging/send-messages.controller.js
  server/routes/trial-management/trial-management.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-432

#433 update pool type print style
  server/routes/reporting/standard-report/definitions.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-433

#434 feature/JM-7323: On Call List
  client/templates/reporting/court-reports.njk
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-434

#429 Feature/JM-6422&6425: Trial Attendance Report & Jury Cost Bill
  client/scss/mod-custom.scss
  client/templates/reporting/court-reports.njk
  client/templates/reporting/standard-reports/trial-select.njk
  server/lib/mod-utils.js
  server/lib/mod-utils.spec.js
  server/routes/messaging/send-messages.controller.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-429

#435 feature/JM-7319: Payment Status Report
  client/templates/reporting/court-reports.njk
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-435

#437 When deferring a juror for a second time I should receive a warning message
  client/templates/juror-management/juror-record/confirm-deferral.njk
  server/routes/juror-management/update/index.js
  server/routes/juror-management/update/juror-update.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-437

#440 Reports Trial Selection Fix
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-440
