Repository hmcts/juror-bureau, pull requests merged in 2024-06, with the labels that each got.

#449 update the select users radios to use the same radio group
  client/templates/administration/users/court-bureau-users.njk
  client/templates/administration/users/users.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-449

#453 csp helmet updates
  server/config/express.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-453

#443 As a jury officer I need to be able to generate a unpaid attendance summary report (FE)
  client/templates/reporting/court-reports.njk
  server/config/validation/report-search-by.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-443

#454 As a system I need to make sure that satellite and primary courts work correctly
  client/templates/juror-management/juror-record/_partials/attendance-table.njk
  client/templates/juror-management/juror-record/attendance.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-454

#455 feature/JM-6465: Deferred List Reports
  client/templates/reporting/bureau-reports.njk
  client/templates/reporting/court-reports.njk
  client/templates/reporting/deferred-list/list-by.njk
  server/config/validation/report-search-by.js
  server/routes/reporting/deferred-list/deferred-list.controller.js
  server/routes/reporting/deferred-list/index.js
  server/routes/reporting/index.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-455

#441 As a jury officer I want to generate a panel ballot report (FE)
  client/templates/pool-management/pool-overview/court-pool-overview.njk
  client/templates/trial-management/trial-detail.njk
  eslint.unignore.js
  server/lib/reports/ballot.js
  server/objects/index.js
  server/routes/pool-management/pool-overview/index.js
  server/routes/pool-management/pool-overview/pool-overview.controller.js
  server/routes/reporting/ballot-cards/ballot-cards.controller.js
  server/routes/reporting/ballot-cards/index.js
  server/routes/reporting/standard-report/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-441

#428 hotfix/JM-7269 - Edit expenses - Able to add more than one full day
  server/objects/expense-record.js
  server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-428

#421 hotfix/JM-6728 - Unable to navigate back to search from summons reply
  client/templates/response/detail.njk
  server/routes/response/detail/detail.controller.js
  server/routes/search/search.controller.js
  server/routes/summons-management/summons-management.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-421

#456 When search results is limited by APP_SETTING.SEARCH_RESULT_LIMIT_TEAM* setting, message isnt shown indicating that it's a limited results set
  client/templates/search/index.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-456

#460 As a system admin, court locations appear that are already assigned
  server/routes/administration/users/assign-courts/assign-courts.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-460

#430 feature/JM-6463: Excused and Disqualified Report
  client/templates/reporting/bureau-reports.njk
  client/templates/reporting/court-reports.njk
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-430

#436 Electronic Police Check Report
  client/templates/reporting/bureau-reports.njk
  server/config/validation/report-search-by.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-436

#452 feature/JM-6450&6488: Pool Statistics & Attendance Data reports
  client/templates/reporting/bureau-reports.njk
  client/templates/reporting/court-statistics.njk
  client/templates/reporting/standard-reports/date-search.njk
  server/config/validation/report-search-by.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/report-export.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-452

#458 Amended styles to fix table overflow breaking footer and hiding conte…
  client/scss/mod-custom.scss
  client/templates/administration/courts-and-bureau.njk
  client/templates/administration/users/assign-courts/_partials/assign-courts-table.njk
  client/templates/administration/users/assign-courts/assign-courts.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-458

#464 renovate thing
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-464

#463 Jury Attendance Audit report - audit report not hyperlink
  client/templates/juror-management/jurors-on-trial/trials-table.njk
  server/routes/juror-management/jurors-on-trial/jurors-on-trial.controller.js
  server/routes/reporting/jury-attendance-audit/index.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-463

#459 Juror number being used in place of pool number on Unpaid Attendance
  client/templates/juror-management/unpaid-attendance.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-459

#444 Feature/jm-6494 - As a SJO I want to be able to generate a juror amendment report
  client/templates/reporting/court-reports.njk
  client/templates/reporting/standard-reports/juror-search.njk
  client/templates/reporting/standard-reports/search-by/juror-amendment.njk
  server/config/validation/juror-search.js
  server/config/validation/juror-search.spec.js
  server/config/validation/report-search-by.js
  server/routes/reporting/index.js
  server/routes/reporting/juror-amendment/index.js
  server/routes/reporting/juror-amendment/juror-amendment.controller.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-444

#467 UAT - lets 2 officers summon for the same pool at the same time
  client/templates/pool-management/additional-summons/index.njk
  client/templates/pool-management/create-pool/summon-citizens/index.njk
  server/objects/index.js
  server/objects/summon-citizens.js
  server/objects/summon-citizens.spec.js
  server/objects/summons-form.js
  server/objects/summons-form.spec.js
  server/routes/pool-management/additional-summons/additional-summons.controller.js
  server/routes/pool-management/create-pool/summon-citizens/summon-citizens.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-467

#468 Responded/Summoned report - formatting slightly off
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/standard-report-print.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-468

#470 When editing a trial the trial date does not show the date originally set, shows todays date instead
  server/routes/trial-management/edit-trial/edit-trial.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-470

#461 feature/JM-6526: Pool ratio report
  client/scss/mod-custom.scss
  client/templates/reporting/bureau-reports.njk
  client/templates/reporting/standard-reports/court-select.njk
  server/routes/reporting/index.js
  server/routes/reporting/pool-ratio/index.js
  server/routes/reporting/pool-ratio/pool-ratio.controller.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-461

#472 Fixed: Officer assigned: AUTO not displayed in response search results
  server/routes/search/search.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-472

#473 Check all on letters not selecting all
  server/routes/documents/letters-list/letters-list.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-473

#469 As a jury officer I want to generate a pool attendances report (FE)
  client/templates/juror-management/attendance.njk
  server/objects/juror-attendance.js
  server/routes/juror-management/juror-management.controller.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-469

#462 Fix how juror-details is retrieved for expenses
  server/objects/juror-record.js
  server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
  server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/draft.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/expense-record.controller.js
  umls/expense-record.plantuml
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-462

#448 Feature/jm-6461: As a jury officer I want to generate a voir dire report (FE)
  client/templates/reporting/court-statistics.njk
  client/templates/reporting/standard-reports/date-search.njk
  server/config/validation/report-search-by.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-448

#479 As as Bureau or court officer I need to generate a pool selection list (FE)
  client/templates/reporting/bureau-reports.njk
  client/templates/reporting/court-reports.njk
  client/templates/reporting/court-statistics.njk
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-479

#477 As a Court officer I want to generate a Completion of service report (FE)
  client/templates/reporting/court-reports.njk
  client/templates/reporting/standard-reports/date-search/fixed-range.njk
  client/templates/reporting/standard-reports/date-search/from-to.njk
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-477

#484 hotfix/JM-7452: Fix if payment audit is empty
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-484

#485 hotfix/JM-7469: Update payment status report grouped header
  server/routes/reporting/standard-report/definitions.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-485

#481 Feature/JM-6420- As a jury officer i want to generate a unpaid attendance report (detailed)
  client/scss/mod-custom.scss
  client/templates/reporting/court-reports.njk
  client/templates/reporting/standard-reports/bespoke-report-body/unpaid-attendance-detailed.njk
  server/config/validation/report-search-by.js
  server/lib/reports/default-layout.js
  server/routes/reporting/bespoke-report/bespoke-report-body.js
  server/routes/reporting/bespoke-report/bespoke-report-print.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-481

#488 hotfix/fix-report-sorting: Update report sorting
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-488

#490 hotfix/JM-6969 - Mark as absent doesn't work from record attendance
  server/objects/juror-attendance.js
  server/routes/juror-management/attendance/attendance.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-490

#486 Hotfix/jm 7243
  client/templates/expenses/_partials/recalculate-error-banner.njk
  server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-486

#476 feature/JM-5906: Reprint Audit Reports
  client/templates/reporting/court-reports.njk
  client/templates/reporting/reprint-audit-report/find-report.njk
  client/templates/reporting/reprint-audit-report/print-redirect.njk
  server/routes/reporting/audit.controller.js
  server/routes/reporting/reprint-audit-reports/index.js
  server/routes/reporting/reprint-audit-reports/reprint-audit-report.controller.js
  server/routes/reporting/standard-report/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-476

#493 Preview Draft Audit Report takes you to a blank screen
  client/templates/reporting/draft-audit.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-493

#482 hotfix/JM-6728b - Cannot navigate back to search results list after viewing a record from the results list
  server/routes/response/detail/detail.controller.js
  server/routes/search/search.controller.js
  server/routes/summons-management/summons-management.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-482

#494 hotfix/JM-7452: Trial Attendance Report - technical error when opening
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-494

#495 hotfix/JM-7509&7510: Juror amendment report title and search
  client/templates/reporting/court-reports.njk
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-495

#497 Financial Audit reports date range is incorrect.
  server/lib/reports/financial-audit.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-497

#498 Selecting Trial on any message causes technical error
  server/routes/messaging/send-messages.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-498

#489 Jury summoning monitor report (FE)
  client/scss/mod-custom.scss
  client/templates/reporting/_common/court-reports-nav.njk
  client/templates/reporting/bureau-reports.njk
  client/templates/reporting/jury-summoning-monitor/index.njk
  client/templates/reporting/jury-summoning-monitor/report.njk
  eslint.unignore.js
  server/lib/reports/single-generator.js
  server/objects/reports.js
  server/routes/reporting/bespoke-report/bespoke-report-body.js
  server/routes/reporting/jury-summoning-monitor/index.js
  server/routes/reporting/jury-summoning-monitor/jury-summoning-monitor-print.js
  server/routes/reporting/jury-summoning-monitor/jury-summoning-monitor.controller.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-489

#465 hotfix/JM-7154 - UAT - Jurors not visible when adding more jurors to panel after empanelment
  client/templates/trial-management/_partials/trial-panel.njk
  client/templates/trial-management/trial-detail.njk
  server/routes/trial-management/trial-management.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-465

#501 Pool Attendances Report - button to open report doesn't appear
  client/templates/juror-management/attendance.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-501

#503 hotfix/JM-6969b - Mark as absent doesn't work from record attendance (hidden absent table)
  client/templates/juror-management/attendance/confirmed/confirmed.njk
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-503

#505 Current Pool Status - Formatting of 'failed to attend'
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-505

#500 Update express-rate-limit to 7.3.1
  package.json
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-500

#506 hotfix/JM-7491 - Request a DOB when entering a paper summons reply
  server/config/validation/date-picker.js
  server/config/validation/paper-reply.js
  server/objects/paper-reply.js
  server/routes/summons-management/update/juror-details.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-506

#507 hotfix/JM-7154b - UAT - Jurors not visible when adding more jurors to panel after empanelment (show 'Panel' jurors only)
  server/routes/trial-management/empanel-jury/empanel-jury.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-507

#504 Error message when reassigning a juror but not selecting a pool appear to be incorrect
  server/config/validation/pool-management.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-504

#508 hotfix/JM-7295 - Pool request subheading appearing on Active Pools screen
  client/templates/administration/users/court-bureau-users.njk
  client/templates/administration/users/users.njk
  client/templates/custom-components/sortable-table/template.njk
  client/templates/juror-management/unpaid-attendance.njk
  client/templates/messaging/_partials/jurors-table.njk
  client/templates/messaging/_partials/trials-table.njk
  client/templates/pool-management/coroner-court/_partials/results-table.njk
  client/templates/pool-management/index.njk
  client/templates/pool-management/pool-overview/bureau-pool-jurors.njk
  client/templates/pool-management/pool-overview/court-pool-jurors.njk
  client/templates/sjo-tasks/uncomplete-service/select-jurors.njk
  client/templates/trial-management/trials.njk
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-508

#499 Report - Yield Performance Report (FE)
  client/templates/reporting/bureau-reports.njk
  client/templates/reporting/standard-reports/date-search/fixed-range.njk
  server/config/validation/report-search-by.js
  server/objects/reports.js
  server/routes/reporting/index.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/yield-performance/index.js
  server/routes/reporting/yield-performance/yield-performance.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-499

#509 Error-handler logging
  server/config/express.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-509

#515 Dependabot/npm and yarn/azure/msal node 2.9.2 1
  yarn-audit-known-issues
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-515

#517 Preview Draft Audit Report takes you to a blank screen
  client/templates/custom-components/letter-flow/redirect.njk
  client/templates/reporting/draft-audit.njk
  client/templates/reporting/reprint-audit-report/print-redirect.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-517

#516 hotfix/JM-7535: Missing max date for juror record deferral
  client/templates/response/process/deferral.njk
  server/routes/juror-management/update/juror-update.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-516

#518 hotfix/JM-7547: Added summons reply button to all tabs of juror record
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-518

#520 Coroners court will let 2 officers summon for a corners court pool at the same time
  client/templates/pool-management/pool-overview/coroner.njk
  server/objects/request-pool.js
  server/routes/pool-management/coroner-court/coroner-court.controller.js
  server/routes/pool-management/pool-overview/pool-overview.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-520

#522 Juror amendment incorrectly named
  client/templates/reporting/court-reports.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-522

#527 bump known issues
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-527

#528 hotfix/JM-7556&7557: Update super navigation access
  client/templates/custom-components/super-navigation/super-navigation.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-528

#529 remove debug logs
  server/routes/authentication/authentication.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-529

#530 update dependencies (13-06-2024)
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-530

#531 hotfix/JM-7553: Summons reply search - retain officer assigned
  client/templates/search/index.njk
  server/routes/search/search.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-531

#532 hotfix/JM-7559: Update SJO approve jurors link
  client/templates/sjo-tasks/_common/sjo-tasks-nav.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-532

#521 When a system admin updates a existing users email to a email that is already in use I get an internal error I should get a Email already in use message
  server/routes/administration/users/edit-user/edit-user.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-521

#512 JDB-5576 - Complete response for updated juror - deferral
  client/js/status.js
  client/templates/response/detail.njk
  server/routes/response/detail/detail.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-512

#537 Chore: sequence diagrams for trial management
  umls/add-panel-members.plantuml
  umls/add-panel-members.svg
  umls/edit-trial.plantuml
  umls/edit-trial.svg
  umls/empanel-jurors.plantuml
  umls/empanel-jury.svg
  umls/generate-panel.plantuml
  umls/generate-panel.svg
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-537

#519 Cannot confirm attendance for yesterday for jurors in a paneled status for previous day
  client/templates/juror-management/attendance/not-checked-out.njk
  server/components/filters/index.js
  server/lib/mod-utils.js
  server/routes/juror-management/attendance/attendance.controller.js
  server/routes/juror-management/attendance/confirm-attendance/confirm-attendance.controller.js
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-519

#536 Fix juror update deferral max date
  client/templates/juror-management/attendance/change-attendance-date.njk
  client/templates/juror-management/juror-record/confirm-deferral.njk
  server/routes/juror-management/attendance/change-attendance-date/change-attendance-date.controller.js
  server/routes/juror-management/update/juror-update.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-536

#523 hotfix/JM-7156 - Incorrect attendance values in overview screen
  client/templates/juror-management/juror-record/overview.njk
  server/routes/juror-management/juror-record/juror-record.controller.js
  server/routes/shared/complete-service/complete-service.controller.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-523

#540 fix circular dependency filters <-> mod-utils
  server/components/filters/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-540

#539 hotfix/JM-7553: Fix failure if officer assigned field isn't filled
  server/routes/search/search.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-539

#534 hotfix/JM-7332 - When editing a juror details I get an incorrect error message
  server/config/validation/edit-juror-details-mod.js
  server/config/validation/paper-reply.js
Labels: bug, ns:juror, prd:juror, rel:juror-bureau-pr-534

#541 Modify confirmed appearance still uses pool number as part of appearance search FE Updates
  server/routes/juror-management/attendance/attendance.controller.js
  server/routes/juror-management/juror-record/modify-attendance/modify-attendance.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-541

#478 Feat/jm 7050
  client/scss/mod-custom.scss
  client/templates/juror-management/_partials/attendance-tab.njk
  client/templates/juror-management/_partials/history-tab.njk
  client/templates/juror-management/_partials/sub-nav.njk
  client/templates/juror-management/juror-record/juror-history.njk
  server/components/filters/index.js
  server/objects/juror-history.js
  server/objects/juror-record.js
  server/routes/juror-management/juror-record/index.js
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-478

#543 Feat/jm 7569
  server/routes/reporting/standard-report/definitions.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-543

#545 Feat (JM-7569) update ballot cards to 2x4 format
  server/lib/reports/ballot.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-545

#547 Update juror record for bureau user not working
  server/routes/juror-management/update/juror-update.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-547

#549 Bug (JM-7178) update date format for BE
  server/routes/juror-management/jurors-on-trial/jurors-on-trial.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-549

#533 Changed signature to firstname and last name
  server/routes/documents/pdf/letter-generator.js
  server/routes/documents/print.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-533

#551 hotfix/JM-7563 Pool type incorrect in pool summary
  client/templates/pool-management/pool-overview/court-pool-overview.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-551

#554 Bug (JM-7547) fix missing enter summons buttons
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-554

#553 Juror history not display trial number or attendance date for trials on trial history events
  client/templates/juror-management/_partials/history-tab.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-553

#556 When editing an expense for approval the extra cost does not save
  server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
  server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-556

#557 When summoning extra jurors "Jurors required to complete the request" shows a negative number if we summon over the required quantity
  client/templates/pool-management/additional-summons/index.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-557

#560 Bug (JM-7601) block empanelling with too many jurors
  server/routes/trial-management/empanel-jury/empanel-jury.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-560

#559 Remove the error that stops future dates for non-attendance days
  client/templates/juror-management/non-attendance-day.njk
  server/config/validation/non-attendance-day.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-559

#548 Mark as undeliverable (bulk) (FE)
  client/js/bulk-undeliverable.js
  client/templates/includes/header_navigation.njk
  client/templates/summons-management/bulk-undeliverable/bulk-undeliverable.njk
  client/templates/summons-management/bulk-undeliverable/table-row.njk
  server/objects/index.js
  server/objects/juror-undeliverable.js
  server/objects/juror-undeliverable.spec.js
  server/routes/juror-management/update/juror-update.controller.js
  server/routes/summons-management/bulk-undeliverable/bulk-undeliverable.controller.js
  server/routes/summons-management/bulk-undeliverable/index.js
  server/routes/summons-management/index.js
  webpack/htmlWebpack.js
Labels: ns:juror, prd:juror, stg/add-or-update, prod/no-changes, rel:juror-bureau-pr-548

#561 Remove the Monday option from yield report not needed
  server/routes/reporting/yield-performance/yield-performance.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-561

#562 System tried rendering a route when it should be rendering a template
  server/routes/pool-management/request-pool/request-pool.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-562

#563 UAT - It shows the wrong time and message in pool history when editing the pool and adding a comment
  client/templates/pool-management/pool-overview/pool-history.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-563

#535 Pool overview selection boxes select all pool members under the hood
  client/templates/layouts/govuk_template.njk
  client/templates/pool-management/pool-overview/_partials/filters.njk
  client/templates/pool-management/pool-overview/bureau-pool-overview.njk
  client/templates/pool-management/pool-overview/court-pool-overview.njk
  server/lib/mod-utils.js
  server/objects/pool-members.js
  server/routes/juror-management/update/juror-update.transfer.controller.js
  server/routes/pool-management/pool-management.controller.js
  server/routes/pool-management/pool-overview/bureau-view.js
  server/routes/pool-management/pool-overview/change-next-due-at-court/change-next-due-at-court.controller.js
  server/routes/pool-management/pool-overview/pool-overview.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-535

#565 Fix (JM-7569) tweak breathing room on adjusted reports
  server/routes/reporting/standard-report/definitions.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-565

#567 Expenses - status undefined
  server/routes/juror-management/expenses/edit-bank-details/edit-bank-details.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-567

#568 Fix reassign to satellite court
  server/routes/juror-management/reassign/reassign.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-568

#574 Fix (JM-7614) force parsing of dates in Europe/London
  server/components/filters/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-574

#572 System allows you to create two trials at the same place with the same case number
  server/routes/trial-management/create-trial/create-trial.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-572

#569 fix the singles transfer from the pool-overview page
  server/routes/pool-management/pool-overview/pool-overview.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-569

#573 Export contact details - if results set >500, returns "no matching results"
  client/templates/messaging/_partials/juror-list-results.njk
  client/templates/messaging/export-contact-details/jurors-list.njk
  server/routes/messaging/export-contact-details.controller.js
  server/routes/messaging/send-messages.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-573

#576 fix select all on bureau letters not selecting the correct jurors
  server/routes/documents/letters-list/letters-list.controller.js
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-576

#578 History does not work on coroners court pool
  client/templates/pool-management/pool-overview/coroner.njk
  server/objects/dataAccessObject.js
  server/objects/request-pool.js
  server/objects/request-pool.spec.js
  server/routes/pool-management/coroner-court/coroner-court.controller.js
  server/routes/pool-management/pool-overview/pool-overview.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-578

#577 Overview section on the overview page for court user not showing correctly
  client/templates/juror-management/juror-record/overview.njk
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-577

#580 When changing a pool number on request-pool journey, the existing pool numbers are not clickable
  server/lib/mod-utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-580

#582 Bug (JM-7582) fix copy for undo failed to attend
  client/templates/sjo-tasks/_common/search-form.njk
  client/templates/sjo-tasks/undo-failed-to-attend/confirm-undo-failed-to-attend.njk
  server/routes/sjo-tasks/sjo-tasks.controller.js
  server/routes/sjo-tasks/undo-failed-to-attend.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-582

#583 Bug (JM-7654) hide overdue banner if juror is completed
  server/routes/response/detail/detail.controller.js
  server/routes/summons-management/summons-management.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-583

#584 Bug (JM-7666) fix select-all ajax behaviour
  server/routes/documents/letters-list/letters-list.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-584

#585 Hotfix/jm 7666
  server/routes/documents/letters-list/letters-list.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-585

#590 Bug (JM-7660) fix missing status on history tab
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-590

#591 Chore: allow deferred jurors to be updated to responded
  client/templates/juror-management/_partials/juror-update-options.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-591

#593 Bug (JM-7669) fix missing jurorNumber on export contact details
  client/js/export-contact-details.js
  server/objects/messaging.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-593

#595 Welsh flag - update juror, set welsh from Y to N, saves value as NULL instead of FALSE
  server/objects/juror-record.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-595

#596 Bug (JM-7675) hide welsh checkbox for jurors summoned to non-welsh courts
  server/routes/summons-management/paper-reply/paper-reply.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-596

#594 Feat (JM-6204) add pdf print option for juror history
  client/scss/mod-custom.scss
  client/templates/juror-management/juror-record/juror-history.njk
  server/routes/juror-management/juror-record/index.js
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-594

#597 Bug (JM-7674) fix phone validation rules
  server/config/validation/paper-reply.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-597
