Repository hmcts/juror-bureau, pull requests merged in 2024-03, with the labels that each got.

#50 jcde-1mar-merge
  Gruntfile.js
  charts/juror-bureau/Chart.yaml
  charts/juror-bureau/values.yaml
  client/js/expenses-summary.js
  client/scss/custom-components/_mod-large-tag.scss
  client/templates/expenses/_partials/recalculate-error-banner.njk
  client/templates/expenses/_partials/summary.njk
  client/templates/expenses/default-expenses.njk
  client/templates/expenses/enter-expenses.njk
  client/templates/juror-management/_partials/heading.njk
  client/templates/juror-management/expense-record/_partials/approval-table.njk
  client/templates/juror-management/expense-record/_partials/draft-table.njk
  client/templates/juror-management/expense-record/_partials/expenses-table-macros.njk
  client/templates/juror-management/expense-record/_partials/for-approval-table.njk
  client/templates/juror-management/expense-record/_partials/sub-nav.njk
  client/templates/juror-management/expense-record/add-smartcard-spend.njk
  client/templates/juror-management/expense-record/expense-record.njk
  client/templates/juror-management/juror-record/_partials/attendance-table.njk
  client/templates/juror-management/juror-record/attendance.njk
  client/templates/juror-management/non-attendance-day.njk
  config/development.json
  config/production.json
  config/test.json
  package.json
  server/app.js
  server/components/filters/index.js
  server/config/validation/add-smartcard-spend.js
  server/config/validation/default-expenses.js
  server/config/validation/default-expenses.spec.js
  server/config/validation/non-attendance-day.js
  server/lib/appinsights.js
  server/lib/launchdarkly.js
  server/lib/mod-utils.js
  server/lib/mod-utils.spec.js
  server/objects/expense-record.js
  server/objects/expenses.js
  server/objects/juror-attendance.js
  server/routes/juror-management/attendance/change-times/change-times.controller.js
  server/routes/juror-management/expenses/add-default-expenses.md
  server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js
  server/routes/juror-management/expenses/enter-expenses/index.js
  server/routes/juror-management/expenses/expenses.controller.js
  server/routes/juror-management/expenses/index.js
  server/routes/juror-management/expenses/non-attendance-day/add-non-attendance-day.md
  server/routes/juror-management/expenses/non-attendance-day/index.js
  server/routes/juror-management/expenses/non-attendance-day/non-attendance-day.controller.js
  server/routes/juror-management/juror-record/index.js
  server/routes/juror-management/unpaid-attendance/expense-record/add-smartcard-spend.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/draft.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/expense-record.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/for-approval.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/index.js
  server/routes/pool-management/pool-overview/pool-overview.controller.js
  umls/add-default-expenses.plantuml
  umls/add-default-expenses.svg
  umls/add-non-attendance-day.plantuml
  umls/add-non-attendance-day.svg
  yarn-audit-known-issues
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-50

#55 update appinsights
  server/lib/appinsights.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-55

#56 update appinsights
  server/lib/appinsights.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-56

#57 alter insights again
  config/development.json
  config/production.json
  config/test.json
  server/lib/appinsights.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-57

#60 reintroduce stg environment
  charts/juror-bureau/values.stg.template.yaml
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-60

#62 jcde-5mar-merge
  client/js/expenses-summary.js
  client/scss/custom-components/_mod-large-tag.scss
  client/templates/custom-components/mod-large-tag/template.njk
  client/templates/expenses/_partials/apply-to-all-days.njk
  client/templates/expenses/_partials/summary.njk
  client/templates/expenses/_partials/time.njk
  client/templates/expenses/bank-details.njk
  client/templates/expenses/enter-expenses-non-attendance.njk
  client/templates/juror-management/_partials/sub-nav.njk
  client/templates/juror-management/approve-expenses/_partials/approve-expenses-table.njk
  client/templates/juror-management/approve-expenses/approve-expenses.njk
  client/templates/juror-management/approve-expenses/cannot-approve.njk
  client/templates/juror-management/expense-record/_partials/draft-table.njk
  client/templates/juror-management/expense-record/expense-record.njk
  client/templates/juror-management/juror-record/expenses.njk
  client/templates/juror-management/juror-record/finance.njk
  client/templates/juror-management/juror-record/notes-edit.njk
  client/templates/response/process/deferral.njk
  client/templates/search/index.njk
  client/templates/trial-management/create-trial.njk
  server/components/filters/filters.spec.js
  server/components/filters/index.js
  server/config/validation/bank-details.js
  server/config/validation/date-picker.js
  server/config/validation/deferral-mod.js
  server/config/validation/deferral-mod.spec.js
  server/config/validation/excusal-mod.js
  server/config/validation/non-attendance-day.js
  server/config/validation/reassign-before-process.js
  server/lib/mod-utils.js
  server/lib/mod-utils.spec.js
  server/objects/expense-record.js
  server/objects/expense-record.spec.js
  server/objects/expenses.js
  server/routes/juror-management/approve-expenses/approve-expenses.controller.js
  server/routes/juror-management/approve-expenses/approve-expenses.md
  server/routes/juror-management/approve-expenses/index.js
  server/routes/juror-management/edit/juror-edit.controller.js
  server/routes/juror-management/expenses/edit-bank-details/edit-bank-details.controller.js
  server/routes/juror-management/expenses/edit-bank-details/edit-bank-details.md
  server/routes/juror-management/expenses/edit-bank-details/index.js
  server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js
  server/routes/juror-management/expenses/expenses.controller.js
  server/routes/juror-management/expenses/index.js
  server/routes/juror-management/expenses/non-attendance-day/non-attendance-day.controller.js
  server/routes/juror-management/juror-record/index.js
  server/routes/juror-management/juror-record/juror-record.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/draft.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/expense-record.controller.js
  server/routes/juror-management/unpaid-attendance/unpaid-attendance.controller.js
  server/routes/juror-management/update/juror-update.controller.js
  server/routes/pool-management/deferral-maintenance/deferral-maintenance.controller.js
  server/routes/search/search.controller.js
  server/routes/trial-management/create-trial/create-trial.controller.js
  server/routes/trial-management/generate-panel/generate-panel.controller.js
  umls/approve-expenses.plantuml
  umls/approve-expenses.svg
  umls/edit-bank-details.plantuml
  umls/edit-bank-details.svg
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-62

#63 jcde-8mar-merge
  client/scss/custom-components/_current-app.scss
  client/templates/administration/_common/bureau-administration-nav.njk
  client/templates/administration/_common/court-administration-nav.njk
  client/templates/administration/_common/system-administration-nav.njk
  client/templates/administration/system-codes-list.njk
  client/templates/administration/system-codes.njk
  client/templates/custom-components/super-navigation/super-navigation.njk
  client/templates/includes/current_app.njk
  client/templates/layouts/default.njk
  client/templates/layouts/govuk_template.njk
  client/templates/pool-management/pool-overview/_partials/filters.njk
  client/templates/pool-management/pool-overview/bureau-pool-jurors.njk
  client/templates/pool-management/pool-overview/bureau-pool-overview.njk
  client/templates/pool-management/pool-overview/court-pool-jurors.njk
  client/templates/pool-management/pool-overview/court-pool-overview.njk
  client/templates/pool-management/pool-overview/pool-jurors-attendance.njk
  client/templates/pool-management/pool-overview/pool-summary.njk
  server/components/auth/index.js
  server/components/auth/user-type.js
  server/config/validation/default-expenses.js
  server/config/validation/default-expenses.spec.js
  server/config/validation/enter-expenses.js
  server/config/validation/enter-expenses.spec.js
  server/lib/mod-utils.js
  server/lib/utils.js
  server/objects/administration.js
  server/objects/expenses.js
  server/objects/pool-members.js
  server/objects/pool-members.spec.js
  server/routes/administration/index.js
  server/routes/administration/system-codes/index.js
  server/routes/administration/system-codes/system-codes.controller.js
  server/routes/index.js
  server/routes/juror-management/update/juror-update.controller.js
  server/routes/login/login.controller.js
  server/routes/pool-management/pool-overview/index.js
  server/routes/pool-management/pool-overview/pool-overview.controller.js
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-63

#66 jcde-11mar-merge
  client/templates/_errors/403.njk
  client/templates/_errors/404.njk
  client/templates/_errors/generic.njk
  client/templates/administration/_common/system-administration-nav.njk
  client/templates/administration/expense-limits.njk
  client/templates/custom-components/letter-flow/redirect.njk
  client/templates/documents/_common/letters-list.njk
  client/templates/documents/_common/show-cause-form.njk
  client/templates/documents/index-court.njk
  client/templates/juror-management/juror-record/attendance.njk
  config/development.json
  config/production.json
  config/test.json
  package.json
  server/config/express.js
  server/config/validation/show-cause.js
  server/config/validation/show-cause.spec.js
  server/config/validation/update-expense-rates.js
  server/config/validation/update-expense-rates.spec.js
  server/lib/mod-utils.js
  server/lib/session-config.js
  server/objects/administration.js
  server/objects/documents.js
  server/routes/administration/administration.controller.js
  server/routes/administration/expense-limits/expense-limits.controller.js
  server/routes/administration/expense-limits/index.js
  server/routes/administration/expense-limits/update-expense-rates-and-limits.md
  server/routes/administration/index.js
  server/routes/administration/system-codes/display-system-codes.md
  server/routes/administration/system-codes/index.js
  server/routes/administration/system-codes/system-codes.controller.js
  server/routes/documents/document-form.controller.js
  server/routes/documents/index.js
  server/routes/documents/letters-list/letters-list.controller.js
  server/routes/documents/pdf/letter-templates.js
  server/routes/documents/print.controller.js
  server/routes/documents/show-cause/index.js
  server/routes/documents/show-cause/show-cause.controller.js
  server/routes/juror-management/edit/juror-edit.controller.js
  server/routes/juror-management/juror-record/juror-record.controller.js
  umls/display-system-codes.plantuml
  umls/display-system-codes.svg
  umls/update-expense-rates-and-limits.plantuml
  umls/update-expense-rates-and-limits.svg
  yarn-audit-known-issues
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-66

#68 hotfix/JM-6577 Digital response is actually paper in the DB
  client/templates/summons-management/_common/details-banner-new.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-68

#72 hotfix/JM-6577 updated to allow method and replyMethod
  client/templates/summons-management/_common/details-banner-new.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-72

#73 update some dependencies
  Gruntfile.js
  client/scss/main.scss
  client/templates/includes/scripts.njk
  client/templates/layouts/govuk_template.njk
  package.json
  server/config/express.js
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-73

#75 Update mod-utils.js
  server/lib/mod-utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-75

#69 add redis docker-compose and update readme.md file
  README.md
  redis/docker-compose.yml
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-69

#78 hotfix/JM-6575 Fixing dates on Todo, waiting info and processed pages
  client/templates/completed.njk
  client/templates/inbox.njk
  client/templates/pending.njk
  client/templates/search/index.njk
  server/objects/responses.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-78

#79 fix frontend failing tests and add missing js script
  client/templates/includes/scripts.njk
  server/objects/deferral-mod.js
  server/objects/deferral-mod.spec.js
  server/objects/summons-management.spec.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-79

#80 hotfix/JM-6578 Fix date on response search results
  client/templates/search/index.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-80

#77 feature/JM-6382&JM-6384: Staff-Management - View, Add, and Edit users
  client/scss/mod-custom.scss
  client/templates/administration/_common/bureau-administration-nav.njk
  client/templates/administration/_common/court-administration-nav.njk
  client/templates/administration/_common/system-administration-nav.njk
  client/templates/administration/users/assign-courts/_partials/assign-courts-table.njk
  client/templates/administration/users/assign-courts/assign-courts.njk
  client/templates/administration/users/assign-courts/remove-court.njk
  client/templates/administration/users/court-bureau-users.njk
  client/templates/administration/users/create-users/confirm-details.njk
  client/templates/administration/users/create-users/user-details.njk
  client/templates/administration/users/create-users/user-type.njk
  client/templates/administration/users/edit-user.njk
  client/templates/administration/users/user-record.njk
  client/templates/administration/users/users.njk
  client/templates/custom-components/autocomplete/template.njk
  client/templates/custom-components/super-navigation/super-navigation.njk
  server/components/auth/index.js
  server/components/auth/user-type.js
  server/config/validation/assign-courts.js
  server/config/validation/assign-courts.spec.js
  server/config/validation/create-users.js
  server/config/validation/create-users.spec.js
  server/lib/mod-utils.js
  server/objects/administration.js
  server/objects/users.js
  server/routes/administration/administration.controller.js
  server/routes/administration/index.js
  server/routes/administration/users/assign-courts/assign-courts.js
  server/routes/administration/users/assign-courts/index.js
  server/routes/administration/users/create-users/create-users.controller.js
  server/routes/administration/users/create-users/index.js
  server/routes/administration/users/edit-user/edit-user.controller.js
  server/routes/administration/users/edit-user/index.js
  server/routes/administration/users/index.js
  server/routes/administration/users/users.controller.js
  server/routes/login/login.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-77

#88 hotfix/JM-6314 - Update to align the postponed letter type with BE
  server/lib/mod-utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-88

#90 Feature (JM-6611) pull juror name from validate movement API for errors
  server/config/validation/juror-bulk-transfer.js
  server/config/validation/juror-bulk-transfer.spec.js
  server/lib/mod-utils.js
  server/routes/juror-management/postpone/postpone.controller.js
  server/routes/juror-management/reassign/reassign.controller.js
  server/routes/juror-management/update/juror-update.transfer.controller.js
  server/routes/pool-management/pool-overview/pool-overview.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-90

#91 hotfix/JM-5746 - Cannot edit juror details from juror record while a summons reply is active
  client/templates/juror-management/juror-record/details.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-91

#89 feature/JM-6254: Manage court room locations
  client/templates/administration/_common/court-administration-nav.njk
  client/templates/administration/room-locations/add-edit-room.njk
  client/templates/administration/room-locations/rooms.njk
  server/components/auth/index.js
  server/config/validation/create-courtroom.js
  server/config/validation/create-courtroom.spec.js
  server/objects/administration.js
  server/routes/administration/index.js
  server/routes/administration/room-locations/index.js
  server/routes/administration/room-locations/room-locations.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-89

#95 updated url routing
  server/routes/administration/room-locations/room-locations.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-95

#98 Added Smart Card spend upper limit
  server/config/validation/add-smartcard-spend.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-98

#100 add known issue for request-promise
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-100

#97 hotfix/JM-5893 - Reassign and Postpone individual flow as court user erroring
  server/routes/juror-management/postpone/postpone.controller.js
  server/routes/juror-management/reassign/reassign.controller.js
  server/routes/juror-management/update/juror-update.controller.js
  server/routes/pool-management/pool-overview/pool-overview.controller.js
  server/routes/summons-management/process-reply/process-reply.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-97

#96 feature/JM-6246: View bank holidays
  client/templates/administration/_common/system-administration-nav.njk
  client/templates/administration/bank-holidays.njk
  server/objects/administration.js
  server/routes/administration/bank-holidays/bank-holidays.controller.js
  server/routes/administration/bank-holidays/index.js
  server/routes/administration/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-96

#105 update_codeowners
  .github/CODEOWNERS
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-105

#74 feature/JM-6252: Court Administration - Manage Judges
  client/templates/administration/_common/court-administration-nav.njk
  client/templates/administration/judges/add-judge.njk
  client/templates/administration/judges/delete-judge.njk
  client/templates/administration/judges/edit-judge.njk
  client/templates/administration/judges/judges.njk
  server/config/validation/edit-judge.js
  server/objects/administration.js
  server/routes/administration/index.js
  server/routes/administration/judges/index.js
  server/routes/administration/judges/judges.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-74

#103 Feature/jm 6250
  client/scss/jd-custom.scss
  client/templates/administration/_common/court-administration-nav.njk
  client/templates/administration/add-non-sitting-days.njk
  client/templates/administration/delete-non-sitting-days.njk
  client/templates/administration/non-sitting-days.njk
  server/config/validation/add-non-sitting-day.js
  server/config/validation/add-non-sitting-day.spec.js
  server/objects/administration.js
  server/routes/administration/index.js
  server/routes/administration/non-sitting-days/index.js
  server/routes/administration/non-sitting-days/non-sitting-days.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-103

#109 hotfix/JM-5919 - Getting error page while creating a Juror record
  server/objects/pool-management.js
  server/objects/pool-management.spec.js
  server/routes/juror-management/create-record-manual/create-record-manual.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-109

#110 update express
  package.json
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-110

#106 Feature/jm 6612
  server/config/validation/complete-service.js
  server/routes/pool-management/pool-overview/pool-overview.controller.js
  server/routes/shared/complete-service/complete-service.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-106

#107 Hotfix/JM-6578 fix date received on response search results
  client/templates/search/index.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-107

#87 feature/JM-6240&JM-6321: Update Court Details
  client/templates/administration/_common/court-administration-nav.njk
  client/templates/administration/_common/system-administration-nav.njk
  client/templates/administration/court-details.njk
  client/templates/administration/courts-and-bureau.njk
  server/components/filters/index.js
  server/config/validation/court-details.js
  server/config/validation/court-details.spec.js
  server/objects/administration.js
  server/routes/administration/court-details/court-details.controller.js
  server/routes/administration/court-details/index.js
  server/routes/administration/courts-and-bureau/courts-and-bureau.controller.js
  server/routes/administration/courts-and-bureau/index.js
  server/routes/administration/index.js
  server/routes/administration/users/assign-courts/assign-courts.js
  server/routes/administration/users/users.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-87

#111 add debug logs
  server/lib/mod-utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-111

#113 hotfix/JM-5704 App crashes when clicking View Summons
  client/templates/juror-management/juror-record/summons.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-113

#112 hotfix/JM-5841
  server/routes/juror-management/update/juror-update.transfer.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-112

#114 Hotfix/jm 6667
  client/templates/juror-management/juror-record/details.njk
  server/routes/response/detail/detail.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-114

#118 hotfix/JM-6659
  server/routes/documents/show-cause/show-cause.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-118

#115 feature/jm-6388 - As a jury officer I need to manually add an attendance day (FE)
  client/templates/juror-management/attendance/add-attendance.njk
  client/templates/juror-management/juror-record/_partials/attendance-table.njk
  client/templates/juror-management/juror-record/attendance.njk
  client/templates/juror-management/juror-record/change-attendance.njk
  server/config/validation/add-attendance.js
  server/config/validation/add-attendance.spec.js
  server/config/validation/change-jurors-attendance.js
  server/lib/mod-utils.js
  server/objects/juror-attendance.js
  server/routes/documents/document-form.controller.js
  server/routes/juror-management/attendance/add-attendance-date/add-attendance-date.controller.js
  server/routes/juror-management/attendance/change-times/change-times.controller.js
  server/routes/juror-management/juror-record/change-attendance/change-attendance.controller.js
  server/routes/juror-management/juror-record/index.js
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-115

#119 hotfix/JM-6690 & JM-6702
  client/js/components/search.js
  client/templates/search/index.njk
  server/components/auth/user-type.js
  server/routes/search/search.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-119

#121 Hotfix/JM-6554
  server/routes/search/search.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-121

#120 Feature/JM-6244
  client/templates/administration/_common/court-administration-nav.njk
  client/templates/administration/expense-limits-court.njk
  client/templates/administration/non-sitting-days.njk
  server/config/validation/update-expense-transport-limits.js
  server/objects/administration.js
  server/objects/court-location.js
  server/routes/administration/expense-limits-court/expense-limits-court.controller.js
  server/routes/administration/expense-limits-court/index.js
  server/routes/administration/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-120

#116 hotfix/JM-6469 - Deferral Reason not displayed on juror overview
  client/templates/dashboard/deferral-excusal.njk
  client/templates/juror-management/edit/juror-edit-deferral.njk
  client/templates/response/_modals/deferral.njk
  client/templates/response/_modals/excusal.njk
  client/templates/response/process/deferral.njk
  client/templates/response/process/excusal.njk
  client/templates/summons-management/deferral.njk
  client/templates/summons-management/excusal.njk
  server/lib/mod-utils.js
  server/objects/excusal.js
  server/routes/juror-management/edit/juror-edit.controller.js
  server/routes/juror-management/update/juror-update.controller.js
  server/routes/response/detail/detail.controller.js
  server/routes/summons-management/paper-reply/paper-reply.controller.js
  server/routes/summons-management/process-reply/reassign-before-process/reassign-before-process.controller.js
  server/routes/summons-management/summons-management.controller.js
  server/routes/summons-management/update/reasonable-adjustments.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-116

#123 Secure cookies
  Dockerfile
  package.json
  server/lib/session-config.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-123

#125 Hotfix/JM-6664 Processing Outcome not displayed on disqualified response
  server/lib/mod-utils.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-125

#124 remove config files and add template file
  .gitignore
  README.md
  config/development.json
  config/environment.template.json
  config/test.json
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-124

#127 fix url builder for adding contact logs
  server/objects/juror-record.js
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-127

#126 Feature/jm 6502
  client/scss/mod-custom.scss
  client/templates/reporting/index.njk
  client/templates/reporting/standard-reports/pool-search.njk
  client/templates/reporting/standard-reports/standard-report.njk
  server/config/validation/pool-search.js
  server/lib/mod-utils.js
  server/lib/utils.js
  server/objects/pool-members.js
  server/objects/reports.js
  server/routes/reporting/index.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-126
