Repository hmcts/juror-bureau, pull requests merged in 2025-09, with the labels that each got.

#1015 task/JS-385: Invite to sentence email not including all jurors previously on trial
  server/routes/messaging/send-messages.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-1015

#1017 Task/JS-467: Refactor response detail controller
  client/js/main.js
  client/js/modal.js
  client/js/status.js
  client/templates/response/_partials/update-header.njk
  server/routes/response/detail/detail.controller.js
  server/routes/response/detail/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-1017

#1018 Task/JS-476: All courts utilisation percentage report
  client/templates/reporting/all-court-utilisation/select-courts.njk
  client/templates/reporting/court-statistics.njk
  server/objects/reports.js
  server/routes/reporting/all-court-utilisation/all-court-utilisation.controller.js
  server/routes/reporting/all-court-utilisation/index.js
  server/routes/reporting/index.js
  server/routes/reporting/standard-report/definitions.js
  server/routes/reporting/standard-report/index.js
  server/routes/reporting/standard-report/standard-report-print.js
  server/routes/reporting/standard-report/standard-report.controller.js
  server/routes/reporting/standard-report/utils.js
  umls/all-court-utilisation-report.plantuml
  umls/all-courts-utilisation-report.svg
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-1018

#1025 JS-531-1 - Bureau homepage dashboard heading update
  server/routes/homepage/homepage.controller.js
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-1025

#1034 JS-271 - Remove legacy SCSS files
  client/scss/01-settings/_colors.scss
  client/scss/01-settings/_global.scss
  client/scss/01-settings/_typography.scss
  client/scss/01-settings/index.scss
  client/scss/02-tools/_mixins.scss
  client/scss/02-tools/index.scss
  client/scss/03-generic/_box-sizing.scss
  client/scss/03-generic/_reset.scss
  client/scss/03-generic/_shared.scss
  client/scss/03-generic/index.scss
  client/scss/04-elements/_main.scss
  client/scss/04-elements/index.scss
  client/scss/05-objects/_buttons.scss
  client/scss/05-objects/_forms.scss
  client/scss/05-objects/_headings.scss
  client/scss/05-objects/_list-bare.scss
  client/scss/05-objects/_modal.scss
  client/scss/05-objects/_navs.scss
  client/scss/05-objects/_phase.scss
  client/scss/05-objects/_sections.scss
  client/scss/05-objects/_tables.scss
  client/scss/05-objects/index.scss
  client/scss/06-components/_arrows.scss
  client/scss/06-components/_backlog.scss
  client/scss/06-components/_calllog.scss
  client/scss/06-components/_changelog.scss
  client/scss/06-components/_edit.scss
  client/scss/06-components/_footer.scss
  client/scss/06-components/_icons.scss
  client/scss/06-components/_layout.scss
  client/scss/06-components/_loadmore.scss
  client/scss/06-components/_notes.scss
  client/scss/06-components/_reallocationmodal.scss
  client/scss/06-components/_response.scss
  client/scss/06-components/_search.scss
  client/scss/06-components/_staff.scss
  client/scss/06-components/_tags.scss
  client/scss/06-components/index.scss
  client/scss/07-trumps/_clearfix.scss
  client/scss/07-trumps/_layout.scss
  client/scss/07-trumps/_utilities.scss
  client/scss/07-trumps/index.scss
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-1034
