Repository hmcts/juror-bureau, pull requests merged in 2025-02, with the labels that each got.

#879 Release5.2
  client/js/messaging-juror-select.js
  client/templates/messaging/select-jurors.njk
  client/templates/response/_partials/juror-details.njk
  client/templates/sjo-tasks/uncomplete-service/confirm-uncomplete.njk
  client/templates/trial-management/returns/return-attendance.njk
  package.json
  server/lib/back-link.js
  server/routes/juror-management/approve-expenses/approve-expenses.controller.js
  server/routes/juror-management/attendance/add-attendance-date/add-attendance-date.controller.js
  server/routes/juror-management/expenses/non-attendance-day/non-attendance-day.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/draft.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/for-approval.controller.js
  server/routes/messaging/index.js
  server/routes/messaging/send-messages.controller.js
  server/routes/sjo-tasks/uncomplete-service.controller.js
  server/routes/trial-management/returns.controller.js
Labels: ns:juror, prd:juror

#882 hotfix/JS-129: Coroner's pool fails if no voters available
  server/routes/pool-management/coroner-court/coroner-court.controller.js
Labels: ns:juror, prd:juror

#890 Task/JS-214: Added notes tab highlight if juror has active notes
  client/templates/juror-management/_partials/sub-nav.njk
  server/routes/juror-management/juror-record/juror-record.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-890

#891 JS-175 - Rounding error on expenditure report
  server/routes/reporting/bespoke-report/bespoke-report-print.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-891

#892 Dev/JS-251 - Quick Links Bureau Homepage
  client/templates/homepage/index.njk
  server/routes/index.js
  server/routes/pool-management/pool-management.controller.js
  server/routes/quick-links/index.js
  server/routes/quick-links/quick-links.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-892

#889 task/JS-212: Update sorting and message for completed replies search
  client/templates/search/index.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-889

#893 Task/JS-268: Enhance Subsistence Calculation - Auto Calculate Court & Travel Time
  client/templates/expenses/_partials/food-and-drink.njk
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-893

#897 hotfix/JS-288: Fix date picker bank holidays named route
  server/routes/date-picker/index.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-897

#898 Task/JS-281: When a juror is over 201 attendance days pay a higher rate
  client/templates/administration/expense-limits.njk
  client/templates/juror-management/expense-record/_partials/expenses-table-macros.njk
  client/templates/juror-management/juror-record/_partials/attendance-table.njk
  server/components/filters/index.js
  server/config/validation/update-expense-rates.js
  server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-898
