Repository hmcts/juror-bureau, pull requests merged in 2025-01, with the labels that each got.

#867 Task/JS-173: Add extra validation to jurors bank account holders name field
  client/templates/expenses/bank-details.njk
  server/config/validation/bank-details.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-867

#869 Task/JS-147: Record 3rd party name and contact details on paper response
  client/templates/juror-management/_partials/third-party-details.njk
  client/templates/response/_partials/juror-details.njk
  client/templates/response/_partials/update-header.njk
  client/templates/response/detail.njk
  client/templates/summons-management/paper-reply/index.njk
  server/config/validation/paper-reply.js
  server/routes/summons-management/paper-reply/paper-reply.controller.js
  server/routes/summons-management/summons-management.controller.js
  server/routes/summons-management/update/juror-details.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-869

#875 hotfix/JS-147b: Fix previous juror dob on summons reply
  client/templates/response/_partials/juror-details.njk
Labels: ns:juror, prd:juror

#878 JS-57a - Revert change to telephone validator regex
  server/config/validation/paper-reply.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-878

#863 Release5.1
  client/js/document-letters.js
  client/templates/documents/_partials/table.njk
  client/templates/expenses/bank-details.njk
  client/templates/juror-management/_partials/third-party-details.njk
  client/templates/response/_partials/juror-details.njk
  client/templates/response/_partials/update-header.njk
  client/templates/response/detail.njk
  client/templates/summons-management/paper-reply/index.njk
  package.json
  server/app.js
  server/config/validation/bank-details.js
  server/config/validation/paper-reply.js
  server/routes/documents/helper/table-generator.js
  server/routes/documents/letters-list/letters-list.controller.js
  server/routes/search/search.controller.js
  server/routes/summons-management/paper-reply/paper-reply.controller.js
  server/routes/summons-management/summons-management.controller.js
  server/routes/summons-management/update/juror-details.controller.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-863

#877 hotfix/JS-129: Coroner's pool fails if no voters available
  server/routes/pool-management/coroner-court/coroner-court.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-877

#874 task/JS-160: Reinstate Middle Option for Returning Jurors
  client/templates/trial-management/returns/return-attendance.njk
  server/routes/trial-management/returns.controller.js
Labels: ns:juror, prd:juror

#873 Task/JS-192: Error when adding attendance at wrong court location
  server/routes/juror-management/approve-expenses/approve-expenses.controller.js
  server/routes/juror-management/attendance/add-attendance-date/add-attendance-date.controller.js
  server/routes/juror-management/expenses/non-attendance-day/non-attendance-day.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-873

#872 task/JS-189: Send a sentence date message for jurors that were on a trail
  client/js/messaging-juror-select.js
  client/templates/messaging/select-jurors.njk
  server/routes/messaging/index.js
  server/routes/messaging/send-messages.controller.js
Labels: ns:juror, prd:juror, rel:juror-bureau-pr-872

#884 task/JS-146: Error when try to uncomplete jurors
  client/templates/sjo-tasks/uncomplete-service/confirm-uncomplete.njk
  server/routes/sjo-tasks/uncomplete-service.controller.js
Labels: ns:juror, prd:juror

#885 JS-177 - Attendance page back link error
  server/lib/back-link.js
Labels: ns:juror, prd:juror

#886 JS-79 - Update package.json metadata
  package.json
Labels: ns:juror, prd:juror

#887 JS-178 - Expenses page back link
  server/lib/back-link.js
  server/routes/juror-management/approve-expenses/approve-expenses.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/draft.controller.js
  server/routes/juror-management/unpaid-attendance/expense-record/for-approval.controller.js
Labels: ns:juror, prd:juror
